### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.97.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [kiwix/kiwix-xulrunner#1]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.97.

**Comment by kelson42** [comment]
You mean in the app or outside the app?

**Comment by locutis-of-borg-1999** [comment]
The info' page in the F-Droid app', under "links".  

Right now, "links" expands to:
    \* Source Code
    \* Issues
    \* Website

**Comment by mvdan** [comment]
This is not a bug in the app, you can just add a changelog link to the fdroiddata metadata file. A markdown file or the github releases page (if it contains the release notes) will do.

**Comment by kelson42** [comment]
@mvdan 
I have created a Android specific CHANGELOG file
https://github.com/kiwix/kiwix/blob/master/android/CHANGELOG

Would you be able to link to it in FDroid?

**Comment by kelson42** [comment]
Changelog pointing to the new file introduced in F-Droid
https://gitlab.com/fdroid/fdroiddata/commit/1803f419
