### ISSUE TITLE
How can I integrate kiwix core to Emacs?

### ISSUE THREAD

**Issue by stardiviner** [kiwix/kiwix-xulrunner#11]
I wish to query kiwix, and return page back to Emacs. So emacs browser can view page.

**Comment by kelson42** [comment]
I don't know how emacs browser mod works but have you tried to play with Kiwix HTTP server kiwix-serve?

**Comment by stardiviner** [comment]
Thanks, I'm developing an Emacs package for accessing Kiwix HTTP server searching.

**Comment by stardiviner** [comment]
Thanks, I'm developing an Emacs package for accessing Kiwix HTTP server searching.

**Comment by stardiviner** [comment]
Thanks, I'm developing an Emacs package for accessing Kiwix HTTP server searching.

**Comment by stardiviner** [comment]
Thanks, I'm developing an Emacs package for accessing Kiwix HTTP server searching.

**Comment by kelson42** [comment]
@stardiviner Cool :) Let us know at the time it works, we have a few emacs users here around :)

**Comment by stardiviner** [comment]
Ok. I will update my repository here. Hope persons who are interested in will involve in.
Here is my repo: https://github.com/stardiviner/kiwix.el
I will update it recently. (It does not have a work version yet)

**Comment by stardiviner** [comment]
I pushed first commit, which is still not working. I will look about it later.

**Comment by stardiviner** [comment]
I find I can't complete my Emacs plugin.
- I tried to use command line tool `kiwix-search`, but it have to specify INDEX file path, locate this file is hard for me, and If library file updated, or library not indexed, but user still want to search.
- I don't know how to use Emacs Lisp code to communicate with **kiwix server**.

I think a better way is let `Kiwix` support search from command line with a simple way:
Like [Zeal](http://zealdocs.org), it supports query from command-line with `$ zeal [SEARCH]`.
And there is a Emacs plugin [zeal-at-point](https://github.com/jinzhu/zeal-at-point) .

**Comment by stardiviner** [comment]
I finished my Emacs package.

Here it is: https://github.com/stardiviner/kiwix.el

I hope Kiwix team can add my project link in Kiwix README, so more user can use it.

**Comment by kelson42** [comment]
@stardiviner I have added a link here http://www.openzim.org/wiki/Readers which is the page where we keep a track of all ZIM related content. Later this year we will create kiwix-serve own project to speed-up/simplify its developement. At this time we will put a word about kiwix.el in its new dedicated READEM. Thank you again for making this possible.
