### ISSUE TITLE
Error Source-Code

### ISSUE THREAD

**Issue by joergre** [kiwix/kiwix-xulrunner#12]
raspberry Pi 2B with Raspbian
# Steps:

```
wget http://download.kiwix.org/src/kiwix-src.tar.xz
sudo su
apt-get install libzim0 liblzma5 libctpp2-2
apt-get install make gcc libtool
tar xvf kiwix-src.tar.xz
cd kiwix-0.9/
./autogen.sh
```
# Error:

```
configure.ac:1836: required file 'static/Makefile.in' not found
```
# Solution:

```
cd kiwix-0.9/
mkdir static
cp Makefile.in static/
./autogen.sh
./configure
make
make install
```
# P.S.:

Thank you for developing Kiwix. I put it in a youth detention center (Judenvollzugsanstallt) and a forensic psychiatry in the context of vocational training in Germany.

**Comment by kelson42** [comment]
Thank you for your bug report. I confirm the bug. Really happy to have feedback about "Wikipedia in Jail" deployments.

**Comment by kelson42** [comment]
We have change the build system recently and now it works well. We also provide nightly bilds for GNU/Linux on ARM here http://download.kiwix.org/nightly/
