### ISSUE TITLE
kiwix/Makefile.am.alt DESTDIR problem

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#127]
**Reported by *anonymous on 2012-06-17 09:56 UTC**
Kiwix attempts to install a symlink outside DESTDIR during \"make install\"

Problem is due to the following in kiwix/Makefile.am.alt
install-exec-hook:
        -ln -s -f $(DESTDIR)$(launcherdir)/kiwix $(bindir)/kiwix

**Comment by kelson42** [comment]
Software is not maintained anymore. We don't use Makefile anymore to compile follower Kiwix Desktop 2.0.
