### ISSUE TITLE
kiwix/{chrome,defaults} DESTDIR twice in install path

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#128]
**Reported by *anonymous on 2012-06-17 10:06 UTC**
During "make install", kiwix attempts to create directories below $(DESTDIR)/$(DESTDIR)

This due to the following in Makefile.in
chromedir = $(DESTDIR)$(pkgdatadir)/chrome
test -z "$(chromedir)" || $(MKDIR_P) "$(DESTDIR)$(chromedir)"
(more occurrences in there, and same for kiwix/defaults)

**Comment by kelson42** [comment]
We don't use the same technology for follower Kiwix Desktop 2.0. Bug does not occur anymore / won't be fixed.
