### ISSUE TITLE
Linux Local "xulrunner" not installed with "make install"

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#129]
**Reported by kelson42 on 2012-11-03 13:48 UTC**
On Linux, if you do not have xulrunner on your system, you need to download it before compiling kiwix. But:
- with "make" a link is not down in directory "kiwix"
- with "make install", xulrunner is not installed on the system

**Comment by ghost** [comment]
I can confirm this problem. xulrunner is not installed on the system when running `make install`. When trying to start kiwix (dynamic build) it says:

```
Error: unable to find the xulrunner binary.: No such file or directory
```

**Comment by kelson42** [comment]
@rashiq @fturco 
We recommend to install it locally. An easy method is explained in the "static" paragraph of the README file. So "make install" is not going to work well if xulrunner is not already installed on the system. Xulrunner being oudated/deprecated we won't invest a lot of time to polish the compilation process. Goal is to code a new UI for the desktop version of Kiwix using Qt. This is on the 2017 roadmap.
