### ISSUE TITLE
Windows NSIS installer "Run kiwix now" without admin priv.

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#130]
**Reported by kelson42 on 2012-11-12 17:47 UTC**
If Kiwix is launched from the installer, it inheritates its admin priviledges and some popular resident Windows programs extending the keyboard to include special Esperanto signs do not work becausethey cannot access the Kiwix window (if Kiwix is launched by clicking a shortcut, it runs as the user and this problem does not appear)

In addition, this is a security issue.

**Comment by kelson42** [comment]
We don't use the NSIS installer anymore with Kiwix Desktop 2.0
