### ISSUE TITLE
Don't include empty and hidden categories

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#131]
**Reported by nemobis on 2013-01-30 18:22 UTC**
In wikipedia_it_all_01_2013 I found the following types of categories which should not be included (nor as links from articles, nor as pages):
1) categories without members,
2) categories containing only pages not included in the ZIM (like templates),
3) hidden categories.

**Comment by kelson42** [comment]
This has finally been fixed in MWoffliner 1.9.
