### ISSUE TITLE
Don't strip interwiki links

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#132]
**Reported by nemobis on 2013-01-30 18:23 UTC**
Interwiki (not interlanguage) wikilinks should not be removed.
For instance, in wikipedia_it_all_01_2013 there are many "Altri progetti" sections where only the link to Commons is a link, because it's in external link form, but all other sister projects are not linked.

**Comment by kelson42** [comment]
This has been fixed a long time ago inMWoffliner
