### ISSUE TITLE
Some unlinked members in categories have weird titles

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#134]
**Reported by nemobis on 2013-01-30 18:35 UTC**
For instance, on [[:Categoria:Pagine protette per minacce legali]] in wikipedia_it_all_01_2013:
    mw:Bar/Caso Zenima
    mw:Bar/Discussioni/Il ritorno di Orazio e Clarabella
and so on for all Wikipedia: pages.

**Comment by kelson42** [comment]
Probably fixed.
