### ISSUE TITLE
installed folder remain unremoved when Kiwix uninstalled in user defined path

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#135]
**Reported by shiva-pyatimath on 2013-02-04 09:59 UTC**
1. Install kiwix user defined path (for ex: c:/myfolder/kiwix..)
1. goto windows start menu->select kiwix unistall option
2. click "NO" button when dialog box pop up with message "Do you want to KEEP your personal datas (bookmarks, notes)?
3. verify, "Kiwix 0.9 rc2 was successfully removed from your computer" message appears
4. go to installed path, defaultly it would be, C:/

**Comment by kelson42** [comment]
We don't provide so far an install for (deprecated) kiwix-xulrunner replacement: kiwix-desktop 2.0. This bug won't be fixed.
