### ISSUE TITLE
Integrity check freezes the UI

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#136]
**Reported by kelson42 on 2011-08-12 11:48 UTC**
Reported by Nikhilsheth:
menu > Tools > integrity check : clicking on it froze my Kiwix and I had to terminate it!

**Comment by ghost** [comment]
I also experience the same problem. But if I wait enough time the integrity check eventually finishes. Tried with Kiwix 0.9 under Gentoo Linux.

**Comment by kelson42** [comment]
Yes, this should be executed in an other thread at the zimlib or kiwix level.

**Comment by kelson42** [comment]
Kiwix Xulrunner is deprecated and replaced with Kiwix Desktop 2.0. Kiwix Desktop 2.0 does not provide anymore an integrity check feature.
