### ISSUE TITLE
Wikivoyage OSM maps should work

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#139]
**Reported by kelson42 on 2013-08-22 21:31 UTC**
See https://en.wikivoyage.org/wiki/Tokyo/Roppongi#See

**Comment by stefangrotz** [comment]
In gerneral the possiblility to download and open osm data would be great and would absolutely support the idea of making the live easier for people without internet. An connection between the wiki and the map would be even better :)

**Comment by kelson42** [comment]
@stefangrotz Yes, I think the problem to solve is how to get maps in ZIM files. We should be able to provide a solution about this in 2017.

**Comment by stefangrotz** [comment]
Any news on this issue?

**Comment by kelson42** [comment]
It basically an issue with the format and the Wikivoyage scrapper:
* see https://github.com/openzim/libzim/issues/136
* https://github.com/openzim/mwoffliner/issues/288

There is no plan to implement this this year. That said this is an important feature we will do, but we have currently other priorities. Might be in 2019 - depending if we have enough budget.

I close that ticket as fundamentally this is the wrong place to handle it and Kiwix desktop is currently being fully rewritten (see https://github.com/kiwix/kiwix-desktop)
