### ISSUE TITLE
Title of the "Open ZIM file" view has the wrong language

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#142]
**Reported by kelson42 on 2014-01-01 17:02 UTC**
In case you have chosen a new language in the seettings, this title keeps the old language. It looks like a kind of cache issue. A real restart of the app is necessary to get this title with the correct language.

See the example, title is in Spanish (old language), but comment in the center of the screen is in French (current UI language).

**Comment by kelson42** [comment]
The panel/view has been renamed in "ZIM Management" but it's still not translated for now... we should have a look to this.

**Comment by mhutti1** [comment]
This is due to lack of translation not a code problem.
