### ISSUE TITLE
Resume Android Wikipedia download

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#144]
**Reported by josephwebber on 2014-02-21 09:51 UTC**
I use the local library internet service and I only get an hour at a time. I would like to be able to download the 12GB Wikipedia to my Nook HD+ but there is no way I can do it directly in an hour.
Is there any other way I can download it (perhaps onto my memory stick) using my download manager? I could then download it an hour at a time using the resume function, then transfer the whole file from memory stick to Nook at home?
I am assuming that when I download to the tablet directly it starts from the beginning each time. I can't tell because I cannot see a progress bar.
Many thanks.

Many thanks.

**Comment by kelson42** [comment]
This is fixed with new Android download manager in version 2.0
