### ISSUE TITLE
Improve User Experience on upgrade of the Android app

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#157]
**Reported by julianharty on 2014-10-09 09:29 UTC**
When the Android app is updated, it seems to lose or ignore previous user-centric information. This information includes:
- The zim files on the user's device
- Favorites within a zim file

The user is treated as a new user, and shown the generic help/getting started page.

Here are some suggestions for possible improvements. Ultimately the aim would be for updates to be seamless and to maintain all the user's settings including their favourites and the current zim file they were reading. 

The following are partial improvements
- store (and detect) they were reading a zim file in the older version and use that info on launch - the ideal option
  If this isn't possible in the interim
- We at least ask them to refresh the app so it finds their zim files
- or we scan the sdcard in the background and automatically find the zim files for them.

**Comment by mhutti1** [comment]
I think the majority of these may be sorted but I will do some more thorough testing once we get a alpha/beta build.

**Comment by kelson42** [comment]
See also #283

**Comment by mhutti1** [comment]
Closing this as I think we have fixed all if not most of these. Any further issues we can open as more specific bugs.
