### ISSUE TITLE
Problem with Nexus 7 II (scan does not detect files - files can not be opened with Kiwix)

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#160]
**Reported by kelson42 on 2014-10-21 13:07 UTC**
1 - With the mit Nexus USB OTG file Manage it's not possible to open a ZIM file with Kiwix by clicking on the ZIM file icon. May possibilities of software are offered... but not Kiwix

2 - In Kiwix itself the scan feature does not detect any ZIM file in the external USB mass storage.

More details at:
https://sourceforge.net/p/kiwix/discussion/604121/thread/ac826ec5/

**Comment by kelson42** [comment]
New versions (6.0+) of Android simply do not allow to read directly contents via OTG cable.
