### ISSUE TITLE
kiwix-serve welcome page in not mobile friendly

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#162]
**Reported by kelson42 on 2014-10-26 11:56 UTC**
The text should be rewrapped correctly.

**Comment by kelson42** [comment]
Here an example of the wrong page suffering of many problems:
[non_responsive_kiwix-serve_welcome_page.zip](https://github.com/kiwix/kiwix/files/380305/non_responsive_kiwix-serve_welcome_page.zip)

**Comment by kelson42** [comment]
What would be nice is to have something liek this:
https://stackexchange.com/sites#

**Comment by matslats** [comment]
I just tried the above non_responsive_kiwix-serve_welcome_page.zip by shrinking it in my browser and it seemed fine. Can we have a better description of the problem?

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-tools#58
