### ISSUE TITLE
path problem with kiwix-serve library

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#165]
**Reported by kelson42 on 2014-10-31 16:27 UTC**
In certain situation, kiwix-serve seems to be unable to read the library.

kelson@camber:/tmp$ ./kiwix/bin/kiwix-serve --library wikipedia_de_all_12_2013.zim.xml 
Unable to open the XML library file 'wikipedia_de_all_12_2013.zim.xml'.

kelson@camber:/tmp/kiwix/bin$ ./kiwix-serve --library ../../wikipedia_de_all_12_2013.zim.xml 
error 2 opening file "/content/wikipedia_de_all_12_2013.zim": No such file or directory
The XML library file '../../wikipedia_de_all_12_2013.zim.xml' is empty (or has only remote books).
Unable to instanciate the HTTP daemon. The port 80 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-tools#57
