### ISSUE TITLE
Kiwix for Android should not crash if ZIM file is invalid

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#168]
**Reported by kelson42 on 2014-11-01 11:04 UTC**
It happens that is the ZIM file is invalid, Kiwix for Android crashes. This should not happen, instead an error indicating that the file is not valid/corrupted should be displayed.

**Comment by jan-wassenberg** [comment]
This appears to be fixed already. I tried a zero-length "ZIM" file, one with random garbage, and RayCharles truncated to 1.1MB; in all cases, it reports an invalid-file error without crashing.

**Comment by kelson42** [comment]
I have also myself done a few tests without finding any problem, but I'm pretty sure that this kind of problematic file exist. We just need to find one. But I close the ticket, there is nothing more we can do at this point. Thx @jan-wassenberg for your feedback.
