### ISSUE TITLE
[Bug] Kiwix for OSX does not want to run on Yosemite [sf#781]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#172]
**Reported by kelson42 on 2014-11-20 13:37 UTC**
With:
http://download.kiwix.org/bin/0.9/kiwix-0.9.dmg

does not unpack correctly on yosemite. A user reported that he gets this error message: "Kiwix is damaged and can't be opened. You should eject the disk image."

**Comment by jan-wassenberg** [comment]
May have been a download error; it works now on El Capitan (10.11.5).

**Comment by kelson42** [comment]
It is really difficult to support all OSX/MacOS versions. At least new Kiwix Desktop 2.0 is in iTunes, so if you see it, this is good. Meanwhile Yosemite is old, there is nothing we will do more here.
