### ISSUE TITLE
[Bug] Indexing require 2 attempts [sf#791]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#175]
**Reported by ybaruch on 2014-12-02 23:06 UTC**
Hi. On a Mac (10.9) Kiwix v. 0.9 crashes the first time "Launch indexing" is tried. After restarting it Kiwix and trying again, indexing works. Thank you & regards.

**Comment by kelson42** [comment]
New version 2.0 of Kiwix Desktop does not allow to index content, as the index is already embedded in the ZIM file. Try http://macos.kiwix.org. This solve the bug.
