### ISSUE TITLE
[Bug] Icons for external links [sf#793]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#176]
**Reported by nobody on 2014-12-05 08:25 UTC**
Thanks for including the small arrows after external links in the latest zim for the english wikipedia. However, other icons still leaves a white space. For example the icon for a pdf, but I think there are more of them. See the attatched image

**Comment by kelson42** [comment]
I'm not really informed about that pb, but without example and because the report is so old, there is really nothing we can do here.

**Comment by kelson42** [comment]
I'm not really informed about that pb, but without example and because the report is so old, there is really nothing we can do here.
