### ISSUE TITLE
[Bug] Empty references [sf#794]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#177]
**Reported by nobody on 2014-12-05 08:44 UTC**
In some articles in the zim for the english wikipedia with images (possibly others too) the  references are empty. For example in the article "Ön, Umeå", see the attached image.

http://en.wikipedia.org/wiki/%C3%96n%2C_Ume%C3%A5

**Comment by kelson42** [comment]
Moved to https://github.com/openzim/mwoffliner/issues/920
