### ISSUE TITLE
[Bug] Cite error after galleries [sf#795]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#178]
**Reported by nobody on 2014-12-05 11:17 UTC**
In the english wikipedia zim with images (possibly others too) an error message appears after galleries in many articles.
"Cite error: There are <ref> tags on this page, but the references will not show without a {{reflist}} template (see the help page)."

For example in "Urania's Mirror", "Medieval art", "Klondike Gold Rush" and many others. See the attached image.

**Comment by rashiq** [comment]
**Updated by kelson42 on 2014-12-06 19:56 UTC**
- **labels**:  --> zim
- **assigned_to**: Emmanuel Engelhart
- **Group**: v0.9 --> None

**Comment by kelson42** [comment]
Probably fixed meanwhile.
