### ISSUE TITLE
[Bug] Android TTS does not work for Dutch [sf#821]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#185]
**Reported by kelson42 on 2015-01-24 08:51 UTC**
TTS does not work for Dutch Wikipedia ZIM file. After investigating the code it seems that the TTS class simply does not access Locale( 'nl' ) although the Free Google voice claims the support of it.

**Comment by rashiq** [comment]
**Updated by kelson42 on 2015-02-23 10:26 UTC**
- **summary**: Android TTS does not work for russian --> Android TTS does not work for Dutch
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1 +1 @@
-TTS does not work on android with ZIM file in russian... although russian seems to be a supported language (by android TTS)
+TTS does not work for Dutch Wikipedia ZIM file. After investigating the code it seems that the TTS class simply does not access Locale( 'nl' ) although the Free Google voice claims the support of it.

```

**Comment by kelson42** [comment]
I re-open that bug... Reason to close it is not clear to me.

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#39
