### ISSUE TITLE
[Bug] OSX Keyboard shortcuts for forward / back. [sf#822]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#186]
**Reported by bjohas on 2015-01-24 14:38 UTC**
There should be keyboard shortcuts for forward / back, such as cmd-[ and cmd-] on OS X.

**Comment by rashiq** [comment]
**Updated by kelson42 on 2015-01-24 22:50 UTC**
- **labels**:  --> OSX

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-01-24 22:50 UTC**
Should be easy to fix... but I don't have an OSX to test. On Windows and linux ctrl+left and ctrl+right work well.

**Comment by rashiq** [comment]
**Commented by bjohas on 2015-01-24 23:27 UTC**
On OS X, cmd-left, cmd-right actually work, which also works in Chrome.

However, cmd-[, cmd-] also work in Chrome, and so perhaps the request would be to add cmd-[ and cmd-].

More importantly, to add something under 'Help' in the kiwix browser that shows keyboard shortcuts?

Thanks!

**Comment by kelson42** [comment]
I'm not sure what cmd + - whould do... but the most common shortcuts with the arrows, this works also with Kiwix Desktop 2.0.
