### ISSUE TITLE
[Bug] on WPAR, external links are not visible [sf#831]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#188]
**Reported by kelson42 on 2015-02-16 12:41 UTC**
It seems there is something wrong with the CSS. It works for LTR languages.

**Comment by kelson42** [comment]
This has been fixed, see for example http://library.kiwix.org/wikipedia_ar_all_novid/A/%D8%A7%D9%84%D8%AC%D9%85%D9%87%D9%88%D8%B1%D9%8A%D8%A9_%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9_%D8%A7%D9%84%D9%85%D8%AA%D8%AD%D8%AF%D8%A9
