### ISSUE TITLE
[Bug] Some Android devices seems to be unable to deal with ZIM chunks [sf#838]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#191]
**Reported by kelson42 on 2015-02-25 16:20 UTC**
See here for example:
https://sourceforge.net/p/kiwix/discussion/604122/thread/b2fddc32/?limit=25#e985

**Comment by mhutti1** [comment]
@kelson42 Do we have any reproduction steps for this?

**Comment by kelson42** [comment]
@mhutti1  I'll try to reproduce the problem and post herea step-by-step procedure.

**Comment by kelson42** [comment]
I confirm the problem. I also think I have found the root cause. In a case of the chunked ZIM file the first file is called foobar.zimaa and it should open foobar.zim.idx... The problem is that it tries to open foobar.zimaa.idx...

**Comment by kelson42** [comment]
@mhutti1 I propose to close the ticket, without repro-case, there is nothing we can do here.

**Comment by mhutti1** [comment]
Agreed
