### ISSUE TITLE
Suggest similarly spelled search results

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#193]
**Reported by rauldelacalle on 2015-03-09 01:16 UTC**
SPANISH;

Buen día.

Descargue la aplicacion Kiwix para android y la instalé. Descargué el Wikcionario en español, lo descomprimí y lo cargue en la memoria externa del telefono inteligente. Desde la aplicación leo el archivo y todo está bien.

Pero cuando escribo una palabra de manera equivocada el Wikcionario no me corrige. Ejemplo: en español la forma correcta es: Zapato. Si escribo sapato la aplicación me dice: Error: "falló la carga del artículo sapato", pero no me corrige debería mostrame las opciones. Es decir que tengo que ser un experto en el idioma para buscar, no me sirve de esa manera pues el objetivo es que me corrija cuando yo estoy equivocado.

Si hago lo mismo en el computador me muestra como opciones:
1. Zapato
2. Calzado
3. Pasta de zapatos
- Es posible mejorar la aplicación para android?
- Estoy fallando en algo?

ENGLISH:

Good day.

Download the Kiwix application for android and I installed it. I downloaded the Wiktionary in Spanish, unzipped it and upload it to the external memory of the smart phone. Since I read the application file and all is well.

But when I write the wrong word Wiktionary does not correct me. Example: in Spanish is written: ZAPATO. If SAPATO write the application tells me: Error: "failed load SAPATO article", but does not correct me should show me the options. You mean I have to be an expert in the language to find, does not help me that way because the objective is to correct me when I'm wrong.

If I do the same on the computer shows me as options:
1. Zapato
2. Calzado
3. Pasta de zapatos
- It is possible to improve the application for android?
- I'm failing at something?

**Comment by rashiq** [comment]
**Updated by kelson42 on 2015-06-23 04:55 UTC**
- **labels**:  --> android
- **Group**: v1.0 --> None

**Comment by mhutti1** [comment]
This appears to be a search limitation. @kelson42 what is the desktop version do, that the app doesn't that makes search more intelligent?

**Comment by Frenzie** [comment]
For search query results it would be nice to make them ignore case, diacritics, and possibly punctuation (except that the matches closest to what you typed should come higher in the results list). Especially on a phone it's much easier to type `deja vu` or `deja-vu` than `déjà-vu`. Basically like Aard Dictionary.

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#41
