### ISSUE TITLE
[Bug] Does kiwix support syntax highlighting ? [sf#864]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#196]
**Reported by hamorabi on 2015-04-08 01:10 UTC**
Hello,
I noticed that programming language code blocks in wikipedia use syntax highlighting to make it easier to read the code. In kiwix ZIM files, this feature is absent. So, I wonder whether this is a bug.
Thanks.

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-04-09 08:13 UTC**
This is probably due to the fact the resourceloader stylesheets are not loaded correctly, so a bug in mwoffliner.

**Comment by rashiq** [comment]
**Updated by kelson42 on 2015-04-09 08:13 UTC**
- **labels**:  --> zim, mwoffliner
- **Group**: v0.9 --> None

**Comment by kelson42** [comment]
It seems to be still buggy

**Comment by kelson42** [comment]
Moved to https://github.com/openzim/mwoffliner/issues/919
