### ISSUE TITLE
[Bug] Kiwix language ISO code support still not complete [sf#867]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#197]
**Reported by kelson42 on 2015-04-14 08:57 UTC**
I have used languages.js (from Kiwix core) to improve www.kiwix.org mobile backend at http://www.kiwix.org/m/. Although this file was improved recently to support all ISO languages, its database is obviously not complete. Many language are not supported and have still their ISO code in the language selectbox.

**Comment by rashiq** [comment]
**Commented by wilfredor on 2015-07-06 20:50 UTC**
I think that its done

**Comment by jan-wassenberg** [comment]
Looks like the language dropdown still contains many (unsupported) 2-3 letter country codes.

**Comment by kelson42** [comment]
We an internal library in Kiwix Android now, so this bug is not valid anymore.
