### ISSUE TITLE
Invalid bookmark creation on Android

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#20]
1 - Click many times on "random" and "bookmark" icons in the action bar (to create dozens of random bookmarks
2 - Open the bookmarks (long clikc on bookmark icon)
3 - Part of the bookmarks listed are listed as content://org.kiwix.zim.base/..... and trying to open these bookmark opens the welcome page of the current ZIM file

The problem probably happens if the HTML is not fully loaded at the time the bookmark icon is clicked. Then the title of the page is probably unknown (HTML not fully parsed).

IMO, if the page is not fully loaded the bookmarking code should be triggered one time the page is loaded (non blocking).

**Comment by EladKeyshawn** [comment]
im still on the version before the long click to open bookmarks and i dont see any problem

**Comment by EladKeyshawn** [comment]
Now i see its on tablet. i got a 4.4.4 android tablet and crashes when trying to open any article not just random

**Comment by EladKeyshawn** [comment]
@mhutti1, @kelson42  Is this still relevant ? as i have tested it and could not reproduce the problem.

**Comment by kelson42** [comment]
Pretty sure if that was not fixed by a better bookmarking approach. Try with and old/lowend/slow device.

**Comment by EladKeyshawn** [comment]
I have a pretty cheap tablet running 4.4.4 and still can't reproduce.

**Comment by mhutti1** [comment]
You need to do it **very quickly** and have the random button in your action bar to allow the quick clicking.

**Comment by kelson42** [comment]
@EladKeyshawn Any way to make this button (bookmark) actionable only at the time the page is completly loaded?

**Comment by EladKeyshawn** [comment]
@kelson42 Yes i'll check that, even though i could no reproduce the problem in anyway

**Comment by kelson42** [comment]
@EladKeyshawn Do a check to be sure you can get the HTML title (so wait the page is fully loaded) and it will fix the problem

**Comment by mhutti1** [comment]
This is a tricky bug to reproduce. I don't know if we can get a 100% way for someone to reproduce unless they have a slow android tablet. My emulator is far to fast.

**Comment by kelson42** [comment]
@mhutti1 I can always reproduce it. At least easy for me.

**Comment by mhutti1** [comment]
@kelson42 Yeah but its the kind of bug that can't be solved without testing and as we can't come up with guaranteed reproduction steps it may not be suitable for GCI at this time.

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#33
