### ISSUE TITLE
[Bug] idexing problems in android. [sf#870]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#200]
**Reported by rauldelacalle on 2015-04-19 22:49 UTC**
Good day.

Download the Kiwix application for android and I installed it in Smartphone and tablet. I downloaded the Wiktionary in Spanish (For Smarthphone) and Wikibooks in Spanish (For tablet), unzipped it and upload it to the external memory of the smart phone and the tablet respectively. Since I read the applications files and all is well.

WIKTIONARY IN SMARTHPHONE:

But when I write the wrong word Wiktionary does not correct me. Example: in Spanish is written: ZAPATO. If SAPATO write the application tells me: Error: "failed load SAPATO article", but does not correct me should show me the options. You mean I have to be an expert in the language to find, does not help me that way because the objective is to correct me when I'm wrong.

If I do the same (ZAPATO) on the computer shows me as options:

1 Zapato (link)
2 Calzado (link)
3 Pasta de zapatos (link)

It is possible to improve the application for android?
I'm failing at something?

WIKIBOOKS IN TABLET:

Problem: Have you written the exact words, otherwise the same message: "failed load NAME article"

It is possible to improve the application for android?
I'm failing at something?
Application requires Indexing?

Thank you.

**Comment by Klimmbimmel** [comment]
Sorry Rashiq, what you expect Kiwix to do is not possible, at least requires a huuuuge amount of work. Fuzzy search it is called and this is a website / Google feature which needs extra computation and programming. Kiwix offers you to access all content and needs you to know the language properly or at least wants you to be an awake and clever guesser :) either you use a 2-language-dictionary if your mother tongue isn't Spanish or try to type it differently. You only need to guess the right beginning '.'=b (thumbs up :)

**Comment by rashiq** [comment]
@Klimmbimmel yes I'm aware - this bug was actually reported by someone on sourceforge and I merely migrated it.

I think we can close this for now.
