### ISSUE TITLE
[Bug] phet.zim does not load on Android [sf#875]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#203]
**Reported by kelson42 on 2015-04-29 11:55 UTC**
No error but unable to load the activities: blanck pages.

Here is the file
http://tmp.kiwix.org/phet.zim

Maybe a problem with AJAX requests... It does not work on Kiwix for Desktops because of this reason.

**Comment by rashiq** [comment]
**Commented by julianharty on 2015-05-29 06:39 UTC**
OK, there seem to be several factors involved which are possible causes & at the moment I suspect we'll need to address several of them before the PhET Simulations will work reliably

http://stackoverflow.com/questions/18428668/how-to-open-a-new-window-from-a-link-in-a-webview-in-a-chrome-packaged-app

There seem to be problems running the JavaScript. (TBC)

**Comment by kelson42** [comment]
A full new version of the phets ZIM has been developed during the 2016 summer hackathon in Italy. See https://github.com/kiwix/phet. It works, we even have now a custom app.
