### ISSUE TITLE
[Bug] On Android, video fullscreen is not possible [sf#884]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#206]
**Reported by kelson42 on 2015-06-04 09:35 UTC**
Steps to reproduce:
- Download a TED ZIM file
- Start to play a video
- Click on the fullscreen buton

Nothing happens, this seems to be related to a security limitation of Android, but there is a workaround in javascript which should be implemented.

Using [this](https://github.com/cprcrack/VideoEnabledWebView) should fix the problem.

**Comment by kelson42** [comment]
@mhutti1 Do you have an opinion about this? How much work would be necessary?

**Comment by mhutti1** [comment]
@kelson42 I will look into it but don't know at the moment.

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#44
