### ISSUE TITLE
[Bug] Portrait view: infoboxes cut off at left border [sf#895]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#210]
**Reported by axel_boldt on 2015-06-18 09:13 UTC**
Running Android 4.4, Cyanogenmod 11 on Samsung Galaxy S2. Kiwix 1.93.

In portrait mode, the infobox at the top of many articles is cut off at the left border, even though there would be enough space to display it in its entirety. It is not possible to scroll horizontally. (In landscape mode the infobox is fully visible.) I have attached a screenshot of the portrait view of the article "Kitzbühel" from the German Wikipedia.

**Comment by kelson42** [comment]
I think this has been fixed meanwhile
