### ISSUE TITLE
[Bug] On Android, pages with "%" character can not be loaded [sf#900]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#212]
**Reported by kelson42 on 2015-07-22 20:13 UTC**
Pages where the title has a % don't load. Try eg, "100% Chance of Rain" or "1%CLUB". 
http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_2015-05.zim

**Comment by jan-wassenberg** [comment]
Possibly related: #222 (cannot search for pages with %)

**Comment by mhutti1** [comment]
@kelson42 I created a zim with 1%CLUB only with zimbalaka and I can't open on desktop either. I can't download full wikipedia on my device to test it with that though so it could be a zimbalaka issue.

**Comment by kelson42** [comment]
@mhutti1 not sure, but might be a problem in the ZIM file in that case. Will try to confirm the problem with a smaller ZIM file than wikipedia_en_all

**Comment by kelson42** [comment]
I confirm the problem. I also think I have found the root cause. In a case of the chunked ZIM file the first file is called foobar.zimaa and it should open foobar.zim.idx... The problem is that it tries to open foobar.zimaa.idx...

**Comment by kelson42** [comment]
I have retested again with wikipedia/wikipedia_fr_all_nopic_2016-06.zim and I confirm the problem, I'am not able to open the article "101%"

**Comment by mhutti1** [comment]
@kelson42 In this case can we assume this is not an issue with android but Kiwix itself?

**Comment by kelson42** [comment]
@mhutti, pretty sure. The "%" is used as meta-character in URLs, this is a URL encoding issue.

**Comment by mhutti1** [comment]
Pretty positive this is a problem with the C++ as it doesn't seem to work on desktop either.

**Comment by kelson42** [comment]
@mhutti1 Will have a looks this WE

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#50
