### ISSUE TITLE
[Bug] Kiwix for Android seems not to be able do deal with article title with '/' [sf#915]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#216]
**Reported by kelson42 on 2015-09-19 19:30 UTC**
Tested with article "AS/400" on WPES. See screenshot for the result.

**Comment by jan-wassenberg** [comment]
Related: #222 (Cannot handle %)

**Comment by mhutti1** [comment]
Is this still an issue? I can load pages such as /dev/null fine.

**Comment by kelson42** [comment]
I have tested again with the exact example give and it works now perfectly.
