### ISSUE TITLE
[Bug] kiwix-0.9+wikiversity_en_all_2015-10.zip home page problem [sf#920]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#219]
**Reported by tim-moody on 2015-10-30 20:02 UTC**
- A gigantic empty space on the offline home page (which is not here in the online version)
- view/discuss links should not be displayed

**Comment by rashiq** [comment]
**Updated by kelson42 on 2015-10-31 13:32 UTC**
- **labels**:  --> zim, mwoffliner
- **summary**: kiwix-0.9+wikiversity_en_all_2015-10.zip missing home page links --> kiwix-0.9+wikiversity_en_all_2015-10.zip home page problem
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1 +1,2 @@
-Fr is OK, but En has big space were links and images should be
+* A gigantic empty space on the offline home page (which is not here in the online version)
+* view/discuss links should not be displayed

```

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-10-31 13:59 UTC**
The online HTML is strange: https://en.wikiversity.org/wiki/Wikiversity_talk:Main_Page/Introduction#Request.CB.90_Remove_.22height.CB.90100.25.22_for_this_box

**Comment by kelson42** [comment]
mwoffliner related problem. Tracked here https://github.com/kiwix/mwoffliner/issues/13
