### ISSUE TITLE
[Bug] Create a new version of Wikipedia for schools [sf#925]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#220]
**Reported by kelson42 on 2015-11-29 15:58 UTC**
A few URLS are wrongly encoded in the ZIM file:
https://twitter.com/KiwixOffline/status/668526027010895872

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-11-29 16:00 UTC**
But original tarball seems to be not online anymore.

**Comment by kelson42** [comment]
This has been done. A backup tarball can be founf here http://download.kiwix.org/other/wikipedia_for_schools_2013.tar.xz
