### ISSUE TITLE
[Bug] Wikivoyage in Farsi  [sf#926]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#221]
**Reported by kelson42 on 2015-11-29 16:28 UTC**
It seems to be impossible to mirror fa.wikivoyage.org with mwoffliner.

**Comment by kelson42** [comment]
We have fa.wikivoyage.org ZIM files meanwhile. Should be anyway a bug for mwoffliner, not for Kiwix.
