### ISSUE TITLE
[Bug] kiwix-serve seems to be unable to search for article with '%' in the title [sf#928]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#222]
**Reported by kelson42 on 2015-12-08 09:11 UTC**
Articles where the title has a % don't load. Try eg, "100% Chance of Rain" or "1%CLUB" in  
http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_2015-05.zim

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-tools#56
