### ISSUE TITLE
[Bug] No text rewrap after manual zooming on Android Lollipop [sf#929]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#223]
**Reported by fagag1 on 2015-12-09 20:40 UTC**
Similar to issue #708 No text rewrap after manual zooming on Android KitKat.

Same problem with Lollipop.

Phone used: Moto G third generation.
Android version: 5.1.1

Thanks!

**Comment by soloturn** [comment]
you saw it doing this on other android versions? it is embarrassing i never noticed doing this ...

**Comment by rashiq** [comment]
@rthurner I just migrated this ticket from sourceforge. Actually only seen this text rewrap on really old devices. I think they removed that feature from the WebView.

**Comment by soloturn** [comment]
best close it then, what you think?

**Comment by rashiq** [comment]
Yep 👍

**Comment by kelson42** [comment]
@rashiq @rthurner You are all fast than I'm ... just closed the one sourceforge
https://sourceforge.net/p/kiwix/bugs/929/
