### ISSUE TITLE
[Bug] Search should be case insensitive even on redirects [sf#931]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#225]
**Reported by the_redburn on 2015-12-13 13:23 UTC**
With the English ZIM, if you search for "port of Virginia", it will find the redirect "Port of Virginia" and redirect you to the article "Virginia Port Authority".
However, if you search for "port of virginia", it won't find it.

This is only an issue with redirects, because you search for "virginia port authority", it will find the article "Virginia Port Authority".

**Comment by kelson42** [comment]
This has been fixed
