### ISSUE TITLE
Mobile style sheet for kiwix-serve

### ISSUE THREAD

**Issue by cartel0x27** [kiwix/kiwix-xulrunner#23]
When browsing from a mobile device to something running kiwix-serve, it would be nice if the server used the mobile style sheets rather than the desktop ones, which look messed up.

**Comment by kelson42** [comment]
Future (soon) ZIM file will be first thought for mobile usage (and also viewable on desktop of course). The implementation of the change has been done and you will soon see such ZIM files published. Thx for your bug report.

See also https://github.com/openzim/mwoffliner/issues/7
