### ISSUE TITLE
[Bug] OSX App forgets all my content after restart [sf#938]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#230]
**Reported by knoxth on 2016-01-31 20:04 UTC**
Running Kiwix 0.9 on OS X (I've seen the same behavior on 10.10 and 10.11), if content is added to My Library -- either by downloading it directly from within the app or by using torrent links and adding manually -- after the app is quit and later launched again, My Library is empty.

Additionally, after re-adding my content to the app with Open, it tells me that my content is not indexed and asks if I want to reindex it. All my content is indexed, I do that as soon as I add it to the app for the first time.

Could this possibly be because I do not have the app and it's data on my internal boot drive in /Applications, but have it on an external drive?

**Comment by kelson42** [comment]
We have fully rewritten Kiwix for OSX. Please have a look to http://itune.kiwix.org. I will close that ticket.
