### ISSUE TITLE
[Bug] kiwix-serve does not serve correctly pages to iPhone [sf#939]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#231]
**Reported by kelson42 on 2016-02-07 13:21 UTC**
This needs to be checked:
1 - connect to the plug
2 - Open a wikipedia article
3 - Go back to the main page and load a TED video
4 - The bar is not shown

**Comment by kelson42** [comment]
@Skylsmoi Seems to work fine now :)
