### ISSUE TITLE
On Android, provide an option to clean history

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#24]
For private reasons, it's important to provide a solution to clean the history. This could be simply a "button" in the settings panel.

**Comment by EladKeyshawn** [comment]
Do we have history saving?

**Comment by kelson42** [comment]
this is in memory - at least.

**Comment by EladKeyshawn** [comment]
Oh ok can do

**Comment by EladKeyshawn** [comment]
Wait... you mean clear app data?

**Comment by kelson42** [comment]
no, only the navigation history for all tab, like on Firefox "Cleran recent history...". That mean cleaning:
- no current open tab
- no current open file
- no history.

**Comment by mhutti1** [comment]
I also added recent searches so that should be cleared as well dbd3eaa28e73b67f50a4fe5aaa60a6ab41a5883a

**Comment by EladKeyshawn** [comment]
Ok i'm on it

**Comment by kelson42** [comment]
@EladKeyshawn Thanks a lot for looking at this. I heard @mhutti1 made a few comments after reviewing your code. Please make a merge request as soon as you have taken them in account.

**Comment by EladKeyshawn** [comment]
@kelson42 Thanks i did not see any comments even though i talked to him..

**Comment by kelson42** [comment]
@mhutti1 
I have tested this new feature and everything seems to work well. My only one problem is: I don't understand what the search history is and why we have one. How does that work? How is that different to the list of open articles (history)?

**Comment by mhutti1** [comment]
Search history clears the list of recent searches that appears if you attempt to search for an article. History clears the history of all tabs.

**Comment by EladKeyshawn** [comment]
@mhutti1 I think what he means is that the recent searches keeps only articles of which you entered into and not anything you search. So the question what is it different than just history of visited articles.

**Comment by mhutti1** [comment]
History of visited articles includes pages that you arrived at by clicking on hyperlinks. This is not yet implemented.

**Comment by EladKeyshawn** [comment]
Yeah but its really similar. @Kelson42 do you think there is a problem with the current implementation?

**Comment by kelson42** [comment]
I'm probably a little bit slow... but I still don't really understand how works the search history and how that is merged to libkiwix suggestions. I propose to simply merge the tow buttons in one "clean history" which does both. This is too subtitle to keep that feature - users will be puzzled (like me). Then we could close the ticket.

**Comment by mhutti1** [comment]
That is what I originally suggested but @EladKeyshawn thought it might be better to have 2 buttons. I am indifferent either way though.

**Comment by kelson42** [comment]
@mhutti1 I can not figure out a use case where a user would have been really annoyed to have both at the same time. @EladKeyshawn  was well inspired (to my opinion) and I was not to not understand him at that time. Good app = simple app,

**Comment by EladKeyshawn** [comment]
@Kelson42 haha did not quite get what you meant and what should be done about it.

**Comment by EladKeyshawn** [comment]
@Kelson42 so you mean we should keep the search the way it is but just revert to having one clean history button?

**Comment by kelson42** [comment]
@EladKeyshawn Yes, this is what I mean.

**Comment by kelson42** [comment]
@EladKeyshawn OK, great, I don't have tested but I assume it works :) Thank you both @EladKeyshawn and @mhutti1, a few users will be really happy with this new feature.
