### ISSUE TITLE
Extract better snippet to store in xapian index

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-xulrunner#242]
**Problem**: the snippets in xapian index has a few issues.
1. A lot of them contains text in infoboxes, thumb image divs, or whatnot divs.
2. A lot of them are cut off in mid sentences.

**Desired**:
use the text of first paragraph as the snippet. And truncate last sentence if that sentence cannot fit.

**Example**: in file "wikipedia_en_simple_all_2016-05.zim", article "Apple cider". The snippet can be seen in the first image, which contains several "Apple juice" and "Not to be confused with". These words shouldn't be here. 

![img_0388](https://cloud.githubusercontent.com/assets/8294252/16028440/48a4d03a-31ad-11e6-8b2d-87bd809dc9b0.jpg)
![img_0389](https://cloud.githubusercontent.com/assets/8294252/16028441/48b197f2-31ad-11e6-9377-5839c70ff264.jpg)

I am not totally familiar with our snippet generation process, but I guess they come from the 'description' META tag ([reference](https://xapian.org/docs/omega/overview.html#html-parsing)). If that is true, then we can solve this by use the text of the first p tag in mw-content-text to generate the snippet.

**Comment by kelson42** [comment]
I don't think that with the current ZIM it is possible to fix all these problems. The code creating the snippet is in indexer.cpp line 176. I think that we might removed the snippet and replace it by a short description of the article. This description should be available in HTML head > description DOM node. For Wikipedia, this description should come from Wikidata (see the description for "parsi" for example https://www.wikidata.org/wiki/Q90). This is how the mobile view/app of Wikipedia works. What do you think?

**Comment by automactic** [comment]
Yep. I like this idea. However, I checked a few articles in the same zim file mentioned above. There is no description in head.

Ex:

```
<head>
<meta charset=\"UTF-8\">
<title>Apple juice</title>
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
<link rel=\"stylesheet\" href=\"../-/s/style.css\">
<script src=\"../-/j/head.js\"></script>
</head>
```

**Comment by kelson42** [comment]
Yes, need to update mwoffliner to put them.

**Comment by kelson42** [comment]
Snippets are not anymore stored in the FT index. The kiwix-lib is not able to compute them on the fly (if necessary/asked by the software), thx to a Xapian feature. I think this should be tested again, and if things are still not working properly, then report them in the kiwix-lib git repo (one issue per idea). @automactic doable?
