### ISSUE TITLE
Kiwix for Android should integrate a feedback system

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#249]
Speaking with the Wikimed community, it's popup that this Wikipedia community would love to get feedback from the field about articles.

To do so it would be greate to have in the wikimed app:
- An option activating a feedback box
- This feedback box would allow to put a text (maybe a picture) to each article (at the end).
- The feedback would be saved locally and each time the device is online, this would be puched as new topic to a pre-defined Wikipedia talk page.

**Comment by kelson42** [comment]
Re-using the code of the Mediawiki feedback extension might be a good idea:
https://www.mediawiki.org/wiki/Article_feedback

**Comment by kelson42** [comment]
@zaeemsiddiq Any news on this? We are almost ready to release kiwix 2.0 (next week) for android and just after it would be a good timing to integrate your work. Are you ready?

**Comment by zaeemsiddiq** [comment]
@kelson42 Hopefully i will be able to finish it by the end of this month. Was busy with other assignment projects

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#52
