### ISSUE TITLE
Android app doesn't show UI localization for Hebrew, Indonesian and Yiddish

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-xulrunner#250]
Hi,

Android app does show UI localization for Hebrew, Indonesian and Yiddish.

This may happen because Java uses the deprecated codes iw, in, and ji instead of the modern codes he, id, and yi.

They should be redirected in the code or by using Java libraries' redirection (sorry, I'm not sure how is it done exactly, but maybe the [Locale class doc](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html) may give a clue).

**Comment by kelson42** [comment]
Fixed. Thx @amire80 for this bug report.

**Comment by amire80** [comment]
Thanks for fixing!
