### ISSUE TITLE
Language list in the settings in the Android app is sorted by Unicode order instead of using the appropriate locale collation

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-xulrunner#251]
For example, if you set your language to Belarusian and go to Settings -> Language, languages whose name begins with the letter 'і' appear in the end, even though it's in the middle of the alphabet. This letter appears after the main alphabet in the Unicode Cyrillic block, but to the users it is confusing and useless.

The app should use the locale's collation for sorting the names instead of the default Unicode order.

**Comment by kelson42** [comment]
I think I have fixed it but I'm not 100% sure. @amire80 if you have a moment I can show you.

**Comment by amire80** [comment]
Catch me some time :)
