### ISSUE TITLE
"w820dp" appears as one of the languages when selecting the language in the settings in the Android app

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-xulrunner#252]
To reproduce:
- Select English as the language.
- Try to select the language again.
- One of the languages is "w820dp".

This name probably doesn't belong there :)

**Comment by kelson42** [comment]
@EladKeyshawn You had introduced this "language" (in "res" directory). I don't know why... but I just have removed it. I suspect that a (buggy) script has generate it, so we need to be careful to what we commit/push to the git repo.

**Comment by EladKeyshawn** [comment]
@kelson42 weird.. since i have not touched anything regarding language so far.
