### ISSUE TITLE
google play market app name and description can not be translated

### ISSUE THREAD

**Issue by danny2008** [kiwix/kiwix-xulrunner#253]
google play market app name and description can not be translated.

My android phone is in hebrew. when I look at the kiwix app page in the play market I see 
that the app description is machine translated. Instead, it should be possible to translate the app name,     short description and the full description on translatewiki.net

**Comment by kelson42** [comment]
Yes, agree, we have no sync for now for the Play store description page. This should be implemented.

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#53
