### ISSUE TITLE
Unable to use kiwix-serve, behind a reverse proxy, in a non-root directory

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-xulrunner#254]
url rewriting did not work for me if kiwix is not mapped to the web root

so mapping to / works (as I remember), but not /kiwix

**Comment by kelson42** [comment]
I need to have a look where exactly in kiwix-serve are the problems... This is definilty a problem a links and accessing content. So we need to tweak the HTML to allow this.

**Comment by tim-moody** [comment]
I am now back so can set up a test environment and try to reproduce the problems I had.

**Comment by kelson42** [comment]
@tim-moody thx

**Comment by tim-moody** [comment]
using apache 2.4 the easiest kiwix.conf file is

ProxyPass /kiwix http://localhost:3000
ProxyPassReverse /kiwix http://localhost:3000

with this, a url like http://192.168.0.9/kiwix/wikipedia_en_all_2015-05/ reaches its target

but links on that page are for example

http://192.168.0.9/wikipedia_en_all_2015-05/A/Kentucky_Derby.html instead of 
http://192.168.0.9/kiwix/wikipedia_en_all_2015-05/A/Kentucky_Derby.html

same is true of images on the page

**Comment by tim-moody** [comment]
would it be acceptable to introduce a command line parameter for url prefix which would get prepended to humanReadableBookId in the href etc.?

the default would be "" which would make it behave as it currently does.

I think this would be an easy way to fix the non-root proxy problem without having to parse the incoming url.

so the parameter would be -u <urlPrefix>, in my case /kiwix

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-tools#54
