### ISSUE TITLE
Bookmarks should be saved with squidb database

### ISSUE THREAD

**Issue by EladKeyshawn** [kiwix/kiwix-xulrunner#255]
Currently bookmarks are saved on obsolete file which can cause problems as well as making them hard to manage, it'd be better to put them in a DB like squidb as i've seen already used for recent searches.

**Comment by kelson42** [comment]
I thought our bookmarks were saved using SQL, so assuming sqlite. You confirm that assumption is wrong? Your ticket would be then pretty important! I got a pretty unhappy user feedback because he has lost all his bookmarks - we need a more robust system.

**Comment by EladKeyshawn** [comment]
Yes when i wrote the bookmarks i've encounter the old annoying system with the txt file bookmarks saving, which caused a lot of exceptions

**Comment by EladKeyshawn** [comment]
@kelson42 I was unsure about the type of file and now checked and indeed its saved on a txt...pretty bad haha

**Comment by kelson42** [comment]
@EladKeyshawn Yes, this is/was an soft architecture error.

**Comment by EladKeyshawn** [comment]
@kelson42 Now bookmarks are on sqidb. I removed the undo since it already looks like too much undo snackbars etc so i decided to disable that.  
7896782

**Comment by kelson42** [comment]
Nice, do users have a migration path? So that this change does not make them loose all their bookmarks?

**Comment by EladKeyshawn** [comment]
@kelson42 No ,  a new table is created. I guess i could check if there exists this txt file and then transfer it to the database.

**Comment by kelson42** [comment]
@EladKeyshawn Thx, this is indee really necessary otherwise many users will complain they have lost their bookmarks

**Comment by mhutti1** [comment]
Also implement #159 

We should save both title and URL. Try use URL and if that fails try title to allow backwards compatibility.
