### ISSUE TITLE
Android settings panel direction should be localised

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#256]
Currently it always displays (both title and content) in left to the right. In Hebrew it should be displayed from the right to the left.

**Comment by EladKeyshawn** [comment]
@kelson42 Also the whole UI like the 2 nav drawers should switch side...otherwise the interface really look bad.

**Comment by kelson42** [comment]
@EladKeyshawn yes. I guess there is switch somewhere to activate to display rtl (instead of ltr)

**Comment by EladKeyshawn** [comment]
@kelson42 Yes there is somewhere in xml definition of elements

**Comment by kelson42** [comment]
Looks like @mhutti1 and @EladKeyshawn can not fix that bug because my fix to #250 implies symlinks... and their (Windows) fs does not support them. @rashiq, would you be able to have a look please?

**Comment by EladKeyshawn** [comment]
@kelson42 Fixed the RTL direction support, the problem that windows users still don't have full language translation working still exists. Anyways its a mild issue.
7896782

**Comment by rashiq** [comment]
Will take a look later today 👍

**Comment by kelson42** [comment]
For me it seems to work :)
Thx @EladKeyshawn
