### ISSUE TITLE
Uninstalling Android app and then reinstalling causes crash

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#258]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.KiwixMobileActivity}: android.database.sqlite.SQLiteException: no such table: Bookmarks (code 1): , while compiling: SELECT DISTINCT Bookmarks.bookmarkStr AS bookmarkStr FROM Bookmarks ORDER BY Bookmarks._id DESC

**Comment by mhutti1** [comment]
@EladKeyshawn can you take a look at this as to test after complete reinstall I have to add code to wipe the database in the onCreate method.

**Comment by EladKeyshawn** [comment]
@mhutti1 Weird... I can't seem to reproduce this problem. Could you please point me on what exactly did you do?

**Comment by mhutti1** [comment]
@EladKeyshawn When I am in android studio and run the app. Then exit and manually uninstall the app in android system. Then start app again in android studio I crash.

**Comment by EladKeyshawn** [comment]
@mhutti1 Exactly as i did right now and it works fine. Are you sure you made an updated pull to your repo? In addition in KiwixDatabase class is there Bookmarks.TABLE in getTables()   ?

**Comment by mhutti1** [comment]
I think that my database was not being updated correctly. This has fixed it on my end. Remember any structural changes to databases should also include code to upgrade from previous versions.
