### ISSUE TITLE
UI Improvements 

### ISSUE THREAD

**Issue by EladKeyshawn** [kiwix/kiwix-xulrunner#259]
I open this issue so we can consult and decide on UI polishes/touch-ups. 

Anyways,  I thought the first step to make the app look really nice, and better from now is to
change the app main colors to something more appealing than the current black.
In addition, in setting i already replaced all check-boxes with switches which look much better, and removed the dividers. Take a look at the attached images and tell me what you think!
![screenshot_2016-07-11-10-29-00](https://cloud.githubusercontent.com/assets/17123769/16723183/2834b290-4754-11e6-8413-65cbbee0f359.png)
![screenshot_2016-07-11-10-29-35](https://cloud.githubusercontent.com/assets/17123769/16723185/2835d1c0-4754-11e6-8a64-76e3494c014b.png)
![screenshot_2016-07-11-10-29-45](https://cloud.githubusercontent.com/assets/17123769/16723184/2835b3fc-4754-11e6-9ec2-f25dbf8b3a36.png)

**Comment by kelson42** [comment]
@mhutti1 @rashiq Any feedback on this?

**Comment by mhutti1** [comment]
I think that the settings menu does look better like this. I am not sure about the colour though. I think you may have a screen dimming app on? I agree black isn't perfect but I personally don't like this colour more.

**Comment by EladKeyshawn** [comment]
@mhutti So experiment and suggest a color... it should some sort of greyish style in my opinion but surprise me 😉

**Comment by automactic** [comment]
@EladKeyshawn I use #4780B6 in the iOS app as the app's theme color.
But bars are blurred in iOS and doesn't use this tint color.

**Comment by EladKeyshawn** [comment]
@chris yes but iOS is pretty much white and more transparent. So its pretty different in terms of color.

**Comment by automactic** [comment]
@EladKeyshawn Yes, I know. But I am (planning to) use #4780B6 as the tint of buttons, switches, etc.

The green switches in your first screenshot looks pretty nice. But wasn't that the default style?

About the app's main color. (I am assuming we are gonna use the main color in navigation bars) I have a few questions:
- Is it a good idea to keep inside of app consistent with the outside of app? I noticed this from Google apps in iOS. Youtube have red icons, the design inside app is also red. Inbox is both blue inside & outside. Same about Facebook. But the thing is our app's icon is black.
- Is it a good idea to change the bottom bar's tint color to keep it consistent with the navigation bar? I didn't see any android app doing that though. 

And also, may I ask @kelson42. In our app icon, the circle below kiwi bird's beak, it it suppose to be an kiwi egg, a ball, a kiwi fruit or something else?

**Comment by EladKeyshawn** [comment]
@automactic It's not necessarily true... the icon which is black on white is just mascot / logo but inside the app the navigation can be something a little tinted. If you notice Wikipedia is also black upon white and the app inside is a bit grey. We just need to figure out what fits best.

**Comment by mhutti1** [comment]
I am not artistic so I don't really have a preference. On the one hand black is simple but on the other hand it is harsh. I really don't have a strong preference.

**Comment by automactic** [comment]
@EladKeyshawn Yeah, I understand. 

Honestly, the gray in your screenshot is not bad. I am also thinking about the tumblr blue/gray. (The app logo's background. [GooglePlay](https://play.google.com/store/apps/details?id=com.tumblr&hl=en))

**Comment by EladKeyshawn** [comment]
@automactic yeah actually the blueish grey of tumblr looks really good

**Comment by kelson42** [comment]
Conclusion? It's like difficult to get a consensus on this, isn't it?

**Comment by EladKeyshawn** [comment]
@kelson42  Yeah it is, but i think we should move on to a better theme anyways. It'll IMO give a fresh feeling to users.

**Comment by ashgrigas** [comment]
Joining late to the conversation but looked at the brand established already on your website and think the black works well with it. If you're looking to change it for a new feeling but stick within the brand you've already established, what about a palette like this:
<img width="1207" alt="screenshot 2016-11-13 14 27 48" src="https://cloud.githubusercontent.com/assets/9436824/20248233/8837adbc-a9ad-11e6-85f9-7b26e5f941c3.png">

You can change the navigation bar, background pane and button color to this palette pretty easily...

Another that feels tied in somewhat with at least the wikipedia content is this one:
<img width="1196" alt="screenshot 2016-11-13 14 30 18" src="https://cloud.githubusercontent.com/assets/9436824/20248244/d8d09c70-a9ad-11e6-97a8-5906ba3a5a3a.png">

In both palette the most bold color would be the button default and press states...

**Comment by rashiq** [comment]
Sorry  joining in really late on this as well, but @ashgrigas's color palette looks really nice!
We should definitely explore some more options. 
I don't really like the standard/default material design colours originally suggested, since they make the app look too generic.

**Comment by mhutti1** [comment]
I have experimented with the second palette changing our primary colour to black and having blue and gray as secondary colours. I also removed the listview dividers. What do you guys think?

![screenshot_20170119-145257](https://cloud.githubusercontent.com/assets/2286937/22111492/695f8912-de57-11e6-8d31-bea31d342a35.png)
![screenshot_20170119-145252](https://cloud.githubusercontent.com/assets/2286937/22111493/69619a86-de57-11e6-9c2d-b95aab6f55d4.png)
![screenshot_20170119-145305](https://cloud.githubusercontent.com/assets/2286937/22111491/695ef77c-de57-11e6-8734-69a92bbce537.png)
![screenshot_20170119-145632](https://cloud.githubusercontent.com/assets/2286937/22111563/9a917edc-de57-11e6-9f1b-8d98c446464f.png)
![screenshot_20170119-150527](https://cloud.githubusercontent.com/assets/2286937/22111860/d336f7de-de58-11e6-9d66-ac7eb83de719.png)

**Comment by EladKeyshawn** [comment]
I think it looks a better, it's one of the changes I wanted to do ;)

**Comment by kelson42** [comment]
@mhutti1 Looks good to me, go ahead with implementation.

**Comment by EladKeyshawn** [comment]
@mhutti1 @kelson42 wouldn't it also look better to change the toolbar to less dark black?

**Comment by mhutti1** [comment]
@EladKeyshawn  I personally think it looks better this way as it matches the navigation buttons. I'm no expert though.

**Comment by EladKeyshawn** [comment]
@mhutti1 Alright 👍
