### ISSUE TITLE
On Android, night mode should keep pictures colors

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#26]
Night mode seems really good for AMOLED displays, but the problem is that when I enable it things look fine only for the page I am on. As soon as I go to another article, the images in it have their color inverted too, so it looks like photographic negatives.

Firstly reported at https://sourceforge.net/p/kiwix/bugs/901/

**Comment by mhutti1** [comment]
I have done some testing and its not looking good. I can invert the images only back to the right colour with javascript but I cant seem to call this before the page is visible resulting in a visible change of image. Its better than nothing but still pretty bad.

**Comment by EladKeyshawn** [comment]
Maybe you can invert it in java code...like changing the colors array back on creation

**Comment by mhutti1** [comment]
The whole webview is inverted in java already and there's no way to pick specific html elements to modify in java.

**Comment by EladKeyshawn** [comment]
Right....a problem

**Comment by EladKeyshawn** [comment]
so maybe the web view should at first be inverted except the picture with js

**Comment by mhutti1** [comment]
That looks even worse as the whole screen changes from white to black after the page has loaded

**Comment by EladKeyshawn** [comment]
Yeah so i think inverting the image as you suggested should be ok for now

**Comment by EladKeyshawn** [comment]
ill let you know if i come up with a solution

**Comment by mhutti1** [comment]
Well playing around with the onProgressChanged event if you can trigger the javascript inject at the correct moment it works seamlessly but the event rarely triggers at the right time and sometimes never at all.I am going to hold out on committing anything till I can play around a bit more but  i'm not hopeful.

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn Then we probably have to propose this feature in the kiwix-lib (c++)

**Comment by mhutti1** [comment]
@kelson42 yeah I think that might be the best solution.

**Comment by mhutti1** [comment]
So I re read our content provider code and managed to work out how to inject the correct css into the binary of the css file.

**Comment by EladKeyshawn** [comment]
@mhutti1 Well done ;)
