### ISSUE TITLE
Android Multiple network related crashes both fatal and silent

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#261]
Losing connection at certain points while attempting to download can cause major errors.

**Comment by rashiq** [comment]
Oh yeah good point! 
The current error handling is very bad :/

**Comment by mhutti1** [comment]
@rashiq If you have time you are welcome to take a look instead of me. I am very new to RxJava and learning on the go. I am happy to do it but it may take some time.

**Comment by mhutti1** [comment]
I have fixed all that I can find but I suspect more will crop up so will leave this issue open for now.
