### ISSUE TITLE
Android Downloaded files should only be visible on complete donwload

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#262]
This could be done by storing file size from web and matching with real size.

**Comment by mhutti1** [comment]
They now appear partially visible and display a warning on attempt to open.

**Comment by kelson42** [comment]
Firefox would rename it .zim.part as long as the download is not over, and move it to .zim at the end of the process. Might make sense to do that anyway to avoid people to believe, the file is already OK.

**Comment by mhutti1** [comment]
Sounds good I will make a new issue
