### ISSUE TITLE
Parts ZIM doe not work with fulltext indexes on Android

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#269]
If the zim file is in parts (zimaa etc), Kiwix for Android will not find the accompanying IDX folder. So you have to have one big ZIM file and a folder with the same name (IDX)

Reported first here:
https://sourceforge.net/p/kiwix/bugs/953/

**Comment by kelson42** [comment]
I'll try to reproduce the problem

**Comment by morloy** [comment]
Same here. 
Can only get full-text search working on Wikivoyage, which is a single ZIM file.
Full-text search on dewiki isn't working for me.

**Comment by kelson42** [comment]
I confirm the problem. I also think I have found the root cause. In a case of the chunked ZIM file the first file is called foobar.zimaa and it should open foobar.zim.idx... The problem is that it tries to open foobar.zimaa.idx...

**Comment by mhutti1** [comment]
@kelson42 I have tested the function so that it matches your specification but can't test fully at the moment.

**Comment by kelson42** [comment]
@mhutti1 
You can rename a zim file to zimaa and see if it works. It should.

**Comment by mhutti1** [comment]
Good Idea. Will test now.

**Comment by mhutti1** [comment]
It works.
