### ISSUE TITLE
Revamp welcome/help pages

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#27]
The current welcome and help pages suffer from following weaknesses:
- It's impossible to come back to the welcome page, one time a file has been loaded
- Both are ugly
- They are not localized

For this reason this ticket ask:
1 - Merge both welcome and help pages. The informations should be more or less kept but the way to present it is free
2 - A fancy/nice/beautiful still should be used. A few graphics are available at https://commons.wikimedia.org/wiki/Category:Kiwix and http://www.kiwix.org/wiki/Category:Visuals
3 - One time, this is done, we will create a solution to translate this on www.kiwix.org and sync things. (@Kelson)

**Comment by mhutti1** [comment]
be8081dd25...cb7f0bf127 @EladKeyshawn :+1:

**Comment by mhutti1** [comment]
I just need to make it prettier now and then it should be ready.

**Comment by kelson42** [comment]
What is also important here is to have a version in English which can be used as a template for other languages. So each sentence, needs to be identifiable with a DOM node with and id. One time we have this I will update the translation automation tool to sync the stuff with translatewiki.net

**Comment by mhutti1** [comment]
@kelson42 No need its now all in strings file.

**Comment by kelson42** [comment]
@mhutti1 OK... it could not be better!

**Comment by mhutti1** [comment]
@kelson42 Yeah Elad and I decided that we needed to get it out of HTML as it was not in the format of the rest of the app.

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn OK, not sure this is the best decision, but if the result is maintainable and looks good, this is OK for me too :)

**Comment by mhutti1** [comment]
@kelson42 When you get time can you checkout the updated design and give feedback if it needs improvement :)

![screenshot_20160830-190454](https://cloud.githubusercontent.com/assets/2286937/18100939/c115a3a4-6ee4-11e6-9140-7f93b78d0124.png)

**Comment by kelson42** [comment]
Nice... plan to make a new beta release end of this week if we close a few tickets more. Will give a feedback then.

**Comment by EladKeyshawn** [comment]
@mhutti1 Pretty neat design! looks really good 😄

**Comment by kelson42** [comment]
@mhutti1 I have tested the new welcome/help and it looks good but one problem:
- Old help is (quickly) displayed if I click on the home icone (welcome page of current ZIM)
- Old help pages should be removed

**Comment by EladKeyshawn** [comment]
@kelson42  I tried you reproduction steps and did not encounter the problem.

**Comment by kelson42** [comment]
@mhutti1 You do not see it because your device is fast, but you have it too, for sure. The old HTML help page is loaded.

**Comment by mhutti1** [comment]
@kelson42 Ah. The old page was removed on english but not on french or german will fix now.

**Comment by mhutti1** [comment]
aba46e63faf675d41dd458fa74af3135a384e988

**Comment by kelson42** [comment]
Great :)))))
