### ISSUE TITLE
[ANDROID] Useless "scanning for ZIM files"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#278]
In Android content manager, switching from "Downloads" to "Local" generates a useless scanning of ZIM files (at least the spider is displayed). It's not the case if I go "remote" to "local". To my opinion, the full fs scanning should happen on demand (or if the local library is really empty).

**Comment by mhutti1** [comment]
Unable to stop it from scanning as for some reason android is recreating view. I think this is beyond my control. I have however made previously found ZIM files load instantly from database.

**Comment by tedaz** [comment]
This issue re-occurred with the current version.

**Comment by kelson42** [comment]
@tedaz Yes, many people complain about it but we have difficulties to get a clear reprocase. May you please give us details like (1) step-by-step procedure (2) The model of your device. That would be really helpful.

**Comment by mhutti1** [comment]
@kelson42  @tedaz I am not sure about the problem here. We cache search results so it doesn't have any negative impact at all. Refreshing after switching tabs in certain conditions helps ensure we have up to date information. Am I missing something?

**Comment by mhutti1** [comment]
Should be fixed by #379. Will need to test though.

**Comment by kelson42** [comment]
@mhutti1 the problem described in that ticket still occurs.

**Comment by kelson42** [comment]
After discussing we should be able to fix that specific problem by just keeping all 3 tabs in memory. This should avoid to recreated the fragment and relaunch the scan.

**Comment by kelson42** [comment]
@mhutti1 Problem fixes :)

**Comment by kelson42** [comment]
@mhutti1 I have to re-open this because we have introduced a regression: After downloading a content, it is not visible in the "Device" tab. IMO, the solution is just to add it "directly/manually" (so without a rescan) to the "local libriary".
