### ISSUE TITLE
[ANDROID] "Downloads" content manager has not the look&feel like the two other tabs

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#280]
It would be better to have a similar display - with progress bar.

**Comment by mhutti1** [comment]
2d982ea4d92ce17d1bb7effdf2c7125825266e14

**Comment by kelson42** [comment]
It's almost perfect, THX! but would that be possible to display here too the icon?

**Comment by mhutti1** [comment]
@kelson42 I think mine does? You mean the favicon right?

**Comment by kelson42** [comment]
sorry, my fault, my example was a ZIM without icon... really unlucky. It works perfectly. Thx again.
