### ISSUE TITLE
Introduce embedded ft_index support to Android 

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#281]

**Comment by kelson42** [comment]
I have added xapian 1.4 and zimlib 1.3 dependencies, still need to change a little bit the JNI and java code to get it working.

**Comment by kelson42** [comment]
We need here to re-use here XapianSearch.cpp in kiwix.c JNI source code.

**Comment by kelson42** [comment]
Example can be taken on kiwix-serve.cpp

**Comment by kelson42** [comment]
Example ZIM file with ft_index included can be found here http://tmp.kiwix.org/zim%2bftindex/

**Comment by kelson42** [comment]
@moosd Any chance for you to have a look to that task this WE? This is one on the last 3 problem we need to fix to release kiwix for android 2.0.

**Comment by souramoo** [comment]
Done! Please test commit 76e6879 for a working (on my end) implementation. Still need to test it on a multizim file, but works on the ones in the folder you linked.

**Comment by kelson42** [comment]
@moosd Thanks. It looks good at a first sight... but any chance to just re-use XapianSearch.cpp? It seems you have re-implemented/duplicate code here?

**Comment by mhutti1** [comment]
I have tested and I don't think that the full text search works with split files.

**Comment by kelson42** [comment]
@mhutti1 I wonder how you have tested this as we do not provide ZIM with embedded ft_index which are splitted!? That said you are perfectly right - but this is not a bug, only a known limitation. We need to develop a zim-split software able to split smartly (keeping the ft_index in one chunk). Later, we should find a solution to save the ft_index itself in chunks which are not over 4GB, to allow to split even big ZIM files (with ft_indexes) in 4GB chunks... But this is future work. What @moosd did, is "only" getting it working with not-splitted ZIM files. Does that work for you?

**Comment by kelson42** [comment]
Workds now:
- with XapianSearcher
- with Splitted files
