### ISSUE TITLE
Find a solution to be able to just pause the TTS

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#286]
Maybe a small panel as overlay on the text with stop/pause/play buttons?

**Comment by mhutti1** [comment]
This looks like it might be challenging and require us re-implementing the way we do text to speech but it should be possible.

**Comment by EladKeyshawn** [comment]
@mhutti1 what are you referring to exactly?

**Comment by mhutti1** [comment]
@EladKeyshawn I think this might be a good [Google Code-in](https://developers.google.com/open-source/gci/) task but I don't know quite how difficult adding pause functionality would be. Have you already almost got there or do you think this would be a feasible task for a student to complete?

**Comment by EladKeyshawn** [comment]
@mhutti1 I think it is pretty feasible, but anyways as I see I've already implemented one 😕

**Comment by mhutti1** [comment]
@EladKeyshawn As far as I can see you have added the stop button but no pause/play or am I missing something?

**Comment by EladKeyshawn** [comment]
@mhutti1 Oh now I got you... you mean like a small bar at the bottom to control the TTS playback ? like going forward backward etc?

**Comment by mhutti1** [comment]
@EladKeyshawn Possibly but for now I think that just pause/play + stop would work.

**Comment by mhutti1** [comment]
Steps to reproduce:
1. Download and open a ZIM file through our app.
2. Click on the menu button and press text to speech.

What you get:
- The text is read out and can be stopped by pressing the stop button at the bottom.

What we want:
- The bottom bar is split in half and contains the words stop and pause (becomes play when paused).
- Pause allows the speech to be paused and then resumed by the user.

**Comment by mhutti1** [comment]
#372

**Comment by kelson42** [comment]
The TTS feature is broken for me. If I can see the new "PAUSE", I can not hear any sound. I have reinstall "Google Play" version 2.0 and there TTS works fine.

**Comment by mhutti1** [comment]
@kelson42 Again it works fine for me.... Will look into reproducing.

**Comment by kelson42** [comment]
@mhutti1 OK, if you are stuck, I can try to figure out if the Android log provides a few hints.

**Comment by mhutti1** [comment]
@kelson42 I think i have got it working in an emulator.

**Comment by LFT09KA** [comment]
Trusted Platform Module 1.2

**Comment by mhutti1** [comment]
@kelson42 This now works for me in the emulator. Can you test on your device.

**Comment by kelson42** [comment]
@mhutti1 THX, yes I will today or tomorrow.

**Comment by kelson42** [comment]
@mhutti1 Well done! Seems to work prefectly for me :)

**Comment by mhutti1** [comment]
@borisfba Thanks for your help 👍
