### ISSUE TITLE
Search for index on internal storage

### ISSUE THREAD

**Issue by morloy** [kiwix/kiwix-xulrunner#287]
I was just trying to use the English Wikipedia on my new FP2.
However, it turned out to be an unsolvable problem since the FP2 exclusively supports FAT on the SD card. Thus, I cannot use the full-text search index, which is more than 7 GiB in a single file for the English Wikipedia.

A very simple solution for this would be to also look in the Kiwix directory in the internal storage for an index directory of the current ZIM file.

Would it be possible to release this as a quick fix for Kiwix 1.99?

**Comment by kelson42** [comment]
@morloy Why not putting everything on your internal memory? Otherwise I'm not sure there is a quick solution to that problem :( Our approach is in the future to propose splitted full_text indexes too.

**Comment by morloy** [comment]
@kelson42 Well, my internal memory only has 32GB, which simply does not fit the 65GB English Wikipedia.

**Comment by morloy** [comment]
Just had a quick look at the new bug fix for using full-text search on split zim files.
I guess the new getDbName() function could be easily extended extract the basename and the dirname of the zim file, and then simply check on the internal and external storage for an index file.

Unfortunately, I don't have an Android development environment set up to give this a try.

**Comment by mhutti1** [comment]
I guess this would be possible but performing a file system scan every time
the user searches would be a performance killer. The best way to do this
would be to also scan for index files in the content manager and then link
the file to the index in a database entry.

**Comment by kelson42** [comment]
I general, considering that in a few months we will remove the additional fulltext indexes (they will be put in the ZIM file), I do not think we should invest time on this. It is not trivial to do it correctly.
