### ISSUE TITLE
./gen-custom-android-build.py fails

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-xulrunner#288]
./gen-custom-android-build.py customapp/wikimed/info.json --on=armeabi used to succeed around end of July, but now fails:
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 96x96 /curation/tools/kiwix/android-custom-RZHBr4/res/mipmap-xhdpi/kiwix_icon.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 256x256 /curation/tools/kiwix/android-custom-RZHBr4/res/drawable/splash_screen.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 72x72 /curation/tools/kiwix/android-custom-RZHBr4/res/mipmap-hdpi/kiwix_icon.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 256x256 /curation/tools/kiwix/android-custom-RZHBr4/res/drawable/splash_screen.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 192x192 /curation/tools/kiwix/android-custom-RZHBr4/res/mipmap-xxxhdpi/kiwix_icon.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 256x256 /curation/tools/kiwix/android-custom-RZHBr4/res/drawable/splash_screen.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 144x144 /curation/tools/kiwix/android-custom-RZHBr4/res/mipmap-xxhdpi/kiwix_icon.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 256x256 /curation/tools/kiwix/android-custom-RZHBr4/res/drawable/splash_screen.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 72x72 /curation/tools/kiwix/android-custom-RZHBr4/res/mipmap-mdpi/kiwix_icon.png

---
## convert /curation/tools/kiwix/android-custom-RZHBr4/ic_launcher_512.png -resize 256x256 /curation/tools/kiwix/android-custom-RZHBr4/res/drawable/splash_screen.png

---
## ./build-android-with-native.py --toolchain --lzma --icu --zim --kiwix --strip --locales --on=armeabi

Traceback (most recent call last):
  File "./gen-custom-android-build.py", line 644, in <module>
    main(jspath, *_options)
  File "./gen-custom-android-build.py", line 611, in main
    step_func(jsdata, *_options)
  File "./gen-custom-android-build.py", line 459, in step_compile_libkiwix
    syscall(command)
  File "./gen-custom-android-build.py", line 118, in syscall
    call(args, shell=shell)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by mhutti1** [comment]
64c33def582a27338abd7fcb533f38c537ca45ba

**Comment by mhutti1** [comment]
There is a slight problem with gradle at the moment though so you might need to revert 0e262a43db376d66b393ed7df2af0860f80951d6 as it has not found its way into the maven repository yet.

**Comment by kelson42** [comment]
@mhutti1 Do we also need to upgrade the android-sdk in src/dependences/ ?

**Comment by mhutti1** [comment]
@kelson42 I don't think so. I think it gets updated automatically, once google push the plugin to maven. If it still hasn't happened in a week I think we will need to reassess the upgrade.

**Comment by tim-moody** [comment]
just ran again ./gen-custom-android-build.py customapp/embedded/ar-med.json  --on=armeabi

which failed with

## convert /curation/tools/kiwix/android-custom-MSZEcG/ic_launcher_512.png -resize 256x256 /curation/tools/kiwix/android-custom-MSZEcG/res/drawable/splash_screen.png

Traceback (most recent call last):
  File "./gen-custom-android-build.py", line 648, in <module>
    main(jspath, *_options)
  File "./gen-custom-android-build.py", line 615, in main
    step_func(jsdata, *_options)
  File "./gen-custom-android-build.py", line 407, in step_update_android_manifest
    os.path.join(ANDROID_PATH, 'src', 'java', 'test', *package_path))
  File "/usr/lib64/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/curation/tools/kiwix/android-custom-MSZEcG/src/java/test/org/kiwix/kiwixmobile'

info.json has

{
  "app_name": "وِيكيبيديا الطبية (بلا اتصال بالانترنت)",
  "package": "org.kiwix.wikipedia.ar.medicine",
  "version_name": "2016-07",
  "version_code": "2",
  "zim_file": "/library/zims/content/wikipedia_ar_medicine_2016-08.zim",
  "embed_zim": true,
  "ic_launcher": "customapp/embedded/ar-medicine-icon.png",
  "enforced_lang": "ar"
}

**Comment by mhutti1** [comment]
Sorry. Should be fixed now.

**Comment by tim-moody** [comment]
Thanks.  The apk built successfully.

The release-unsigned fails to install after downloading from Internet in a Box.  The debug installs.  Is this expected?

**Comment by mhutti1** [comment]
If its unsigned then I might not install (especially if something has installed before) correctly as far as I know but I think @kelson42 might know more than me.

**Comment by kelson42** [comment]
@tim-moody Yes, if apps are unsigned (with a valid google key) then you need to configure the device to allow this. I close the ticket as the original ticket has been fixed by @mhutti1
