### ISSUE TITLE
Overlaying Help screen on first launch of article

### ISSUE THREAD

**Issue by EladKeyshawn** [kiwix/kiwix-xulrunner#29]
Currently when a user first launches the app, selects a zim file and article... I can't see a way in which the user will know there is an option like swiping to the left for the Content drawer (There is no icon or else to indicate its existance). 
So i thought it might be helpful to have a one-time help on 1st launch overlaying activity to inform the user of it.

**Comment by kelson42** [comment]
Yes. We could propose a system of hints/tips which display as overlay at the start. A dialog would be displayed, displaying a tip. The user would have the possibility to click "next" (to get an other hint) or to quit to make this dialog/overlay invisible.
