### ISSUE TITLE
[ANDROID] Can not leave "download manager" under certain circonstances

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#292]
Steps:
1 - Start a download with download manager
2 - Quit the app / close all apps
4 - Click on the notification about the current download
5 - Kiwix is open a the "downoads" tab of the content manager
6 - Try to exit this panel (top right left pointing arrow)

I get
- The panel always reloading

I want
- To come back to the article display panel

**Comment by mhutti1** [comment]
@kelson42 I can't reproduce this one.

**Comment by mhutti1** [comment]
@kelson42 Ah. I have made a link. You are having the same issue as with #36. Currently we quickly open the main activity on both widget start and download click before switching to the correct activity. Your device for some reason either isn't opening the main activity at all or somehow forgets it ever did. I will now look into more.

**Comment by mhutti1** [comment]
@kelson42 Can you check Settings > System > Developer options > Apps > Don't keep activities is false?

**Comment by kelson42** [comment]
@mhutti1 Yes, your guess with #36 sounds pretty good to me. I confirm it works if the option is desactivated. The option is activated on my tablet. I had forgotten about this. The reason is that in the past we did not care about this and have got a pretty serious amount of complains if the app were not working correctly with this option. It looks like many people with low-end android have taken the habit to activate this option to save memory (for good or bad reasons, I can not judge... and in fact it does not matter). Everything should be done to get the app working with this option activated, it should be the case with the 1.99.

**Comment by mhutti1** [comment]
@EladKeyshawn Thats looking good for me. Well done! Spent 2 hours trying to get this down but kept facing different issues. This looks like its sorted it. Just wait for @kelson42 to confirm it has also worked for him.

**Comment by mhutti1** [comment]
:+1:

**Comment by EladKeyshawn** [comment]
Thanks ! we also need to fix some really common issue where when you come back to main article page, the current tabs are destroyed and it loads a blank page

**Comment by EladKeyshawn** [comment]
@mhutti1 I'll post an issue later

**Comment by mhutti1** [comment]
@EladKeyshawn I think that might be the same as #283 but am not certain.

**Comment by EladKeyshawn** [comment]
@mhutti1 No , it's not the same it's just loading blank page almost always when returning from content manager. I don't know how this has gone unnoticed for so long

**Comment by mhutti1** [comment]
@EladKeyshawn Yeah but it might be the same root cause. Idk you can see.

**Comment by mhutti1** [comment]
@EladKeyshawn I made a mistake. Your changes don't fix this issue fully but they do when combined with mine. I need to push mine as well. This is very weird.

**Comment by EladKeyshawn** [comment]
@mhutti1 I checked it actually solves it, maybe there is a case where it doesn't

**Comment by mhutti1** [comment]
@EladKeyshawn Yes but it doesn't solve widget as well. My code solves that.

**Comment by EladKeyshawn** [comment]
@mhutti1 yeah of course I just haven't fixed it for the widget yet

**Comment by mhutti1** [comment]
@EladKeyshawn Oh ok. Can you look at that then. My code is not as nice as yours. If you can fix that too it would be great.

**Comment by EladKeyshawn** [comment]
@mhutti1 Yeah no prob ;)

**Comment by EladKeyshawn** [comment]
@mhutti1  I just thought about it, and i think that actions performed from the widget are not supposed to direct you to the main activity with the back arrow. The user wants to search or go to bookmarks directly and when he hits back button it should terminate the app. I think Wikipedia app and others also do that.
tell what you think ;)

**Comment by mhutti1** [comment]
@EladKeyshawn Yes you are right. But at the moment clicking an item does not open it.

**Comment by EladKeyshawn** [comment]
@mhutti1 What do you mean? every specific item on the widget opens

**Comment by mhutti1** [comment]
@EladKeyshawn If you are in don't keep activity mode and you try to search after clicking the search widget then the page refreshes and doesn't open.

**Comment by EladKeyshawn** [comment]
@mhutti1 In this case the search widget is of no use anyways, so we need to fix this.
