### ISSUE TITLE
Allow bookmarks to be sorted into folders

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#295]
It should be possible to create folders to easily sort bookmarks.

**Comment by EladKeyshawn** [comment]
:+1:  nice suggestion

**Comment by mhutti1** [comment]
Was not my idea :P One of our users suggested it on google play. Now we can make this dream a reality for him/her.

**Comment by kelson42** [comment]
Was also reported here https://sourceforge.net/p/kiwix/feature-requests/889/

**Comment by mhutti1** [comment]
I think this would be suitable for GCI if we split it into 2 sub-tasks of:
1. Create the UI with a placeholder array of folder names.
2. Update the database to allow persistence.

**Comment by kelson42** [comment]
@mhutti1 OK for me if you have a pretty clear idea how this feature should really looks like. On my side I do not know how to provide all of this (add/move/delete folder/booksmarks) with a simple UI.

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#55
