### ISSUE TITLE
Reduce memory consumption with Android custom apps with embedded ZIM

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#297]
We have a working system to build custom apps with embedded ZIM files (see #6). The only way to have it working correctly is to use the "assets". The problem with that solution is that you can not access it directly because you do not have a filehandle. As a consequence:
- It use twice more storage memory (one time in assets, on time copied somewhere on the fs)
- Decompression is pretty stupid and use a lot of memory which cause install process crashes on low-end devices with big APK.

A solution could be to access directly the content in the asset file:
http://www.50ply.com/blog/2013/01/19/loading-compressed-android-assets-with-file-pointer/#comment-1850768990

**Comment by kelson42** [comment]
Have talked to a Google developer and it seems to be a "standard" way of doing... even if not well enought documented. That said, this method will add an overhead (zip decompressions)... that said this might be not much worse (in term of app perfomance).

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#56
