### ISSUE TITLE
Kiwix unable to save content in the external SD card

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#300]
I have a 128GB external SD card, almost empty. Kiwix is unable to deal with it neither automatically nor propose a way to choose the storage: It tells me I can not download (a big content) because I do not have enough space. Assuming most smartphones has a limited internal storage, this is a real problem because we do not propose any alternative (to the download manager) solution to get the content.

**Comment by mhutti1** [comment]
If this is essential then I think the only solution is a file-system select dialog with file-systems coded for each specific manufacturer (Samsung being the main issue).

**Comment by kelson42** [comment]
@mhutti1 If this is the best (or less worse) solution, then we have to do it and start this. Maybe there is already a library to help this somewhere? We do not need to make it perfect at first, but we can have a default behaviour which can be tweaked via an hardcoded table (device -> mounting points).

**Comment by mhutti1** [comment]
There are libraries out there to do something like this. We could let the user choose a folder with some of them. I will experiment.

**Comment by mhutti1** [comment]
I couldn't find a library to meet our needs so I decided to create my own as a learning experience.

**Comment by EladKeyshawn** [comment]
@mhutti1  Well done man

**Comment by mhutti1** [comment]
https://github.com/mhutti1/android-storage-devices (Work in Progress)

**Comment by mhutti1** [comment]
@kelson42 When you get the time can you test with your tab. I only have an emulated SD card so I can't know if this works.

**Comment by mhutti1** [comment]
Just realised one of the method's i'm using only supports Kitkat and up so will have to write a legacy method for Jelly Bean. (If that's what you are running then that might explain your issues @kelson42)

**Comment by mhutti1** [comment]
7397023448da4dea0fdcba2b2450a24bfa00b56a Might have fixed something.

**Comment by kelson42** [comment]
I wanted to try this, but in the "remote" tab, I always get "not network connection"... not sure if this is related to #309.

**Comment by mhutti1** [comment]
Yes it is will see if I can fix #309 tonight

**Comment by mhutti1** [comment]
@kelson42 I have now closed #309 and you should be able to test again.

**Comment by kelson42** [comment]
@mhutti1 Thanks! I have tested and it looks almost perfect: I'm able to save to my sd card. But there is a problem with the error message displayed if you do not have enough space. It tells 0 MB space left... but in fact I have more.

**Comment by mhutti1** [comment]
Should be a simple fix. I will also try to guide the user to the device
selection screen is there is not enough space.

**Comment by kelson42** [comment]
@mhutti1 Other small detail: I do not have tested but this new settings should not be displayed in case of a custom app.

**Comment by mhutti1** [comment]
Pretty sure I already fixed that in but will test.

**Comment by morloy** [comment]
Would this also help to load existing content from the SD card?

At the moment I do not understand how to open any ZIM file that I downloaded on the computer and copied to the SD card manually.

**Comment by mhutti1** [comment]
No it won't effect that at all. If we don't detect your file already then
file a separate bug report with the specifics.

**Comment by kelson42** [comment]
@mhutti1 Free space correctly detected now :+1:
