### ISSUE TITLE
Kind of instability with 2.0

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#301]
I have tested 30 minutes git master and it is in general it seems to be stable, but I still have achieved to get it crashed 3 times during that perior... unfortunately without being able to identify a clear pattern. That said it seems to be related to the downloading of a file. Here is a log of the last crash;

D/LightsService( 2817): [SvcLED]  setSvcLedLightLocked :: Current SvcLED(id=3) maintains its priority right
D/PersonaManager( 3106): isKioskContainerExistOnDevice
D/PersonaManager( 3106): isKioskContainerExistOnDevice
D/Briefing.SLog( 3246): [Briefing]>>> BNLS:63 [0:0] onNotification Removed : orgkiwixkiwixmobile
D/ApplicationPolicy( 2817): isStatusBarNotificationAllowedAsUser: packageName = org.kiwix.kiwixmobile,userId = 0
V/ApplicationPolicy( 2817): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
D/AndroidRuntime( 4217): Shutting down VM
E/AndroidRuntime( 4217): FATAL EXCEPTION: main
E/AndroidRuntime( 4217): Process: org.kiwix.kiwixmobile, PID: 4217
E/AndroidRuntime( 4217): java.lang.IllegalStateException: Fragment DownloadFragment{3e45a00f} not attached to Activity
E/AndroidRuntime( 4217):    at android.support.v4.app.Fragment.getResources(Fragment.java:646)
E/AndroidRuntime( 4217):    at org.kiwix.kiwixmobile.downloader.DownloadFragment$DownloadAdapter.updateProgress(DownloadFragment.java:112)
E/AndroidRuntime( 4217):    at org.kiwix.kiwixmobile.downloader.DownloadService$1.run(DownloadService.java:170)
E/AndroidRuntime( 4217):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 4217):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4217):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 4217):    at android.app.ActivityThread.main(ActivityThread.java:6117)
E/AndroidRuntime( 4217):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4217):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4217):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime( 4217):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
D/WindowManager( 2817): showStatusBarByNotification() mOpenByNotification=false
V/ApplicationPolicy( 2817): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
D/PanelView( 3106): There is/are notification(s) 
D/PanelView( 3106): kidsfalse mQsExpansionEnabled:true

**Comment by mhutti1** [comment]
Closing this as I have fixed this error. If new ones arise we can open new tickets.
