### ISSUE TITLE
Improve timing for "Please rate" dialog box

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#303]
The "Please rate" dialog box is probably the feature with the best ratio work/impact we have ever done. It has not only achieved to get more rates, but also more good rates. These rates are really important in general to get higher in the ranking but also to help an app to take off. Both of these impacts are really important to increase apps audience. So, I'm really happy to have it and to see the positive impact.

That said, I think we could still improve it a little bit by choosing the moment where it is displayed a little bit more carefully. I have remarked that in my case it's often displayed pretty early in the process after installation - often at a moment where I'm still discovering the app.

I would preferred to be asked a little bit later, one time I got used with the app, and I think we should improve our ration good/bad ratios, by asking a little bit later after the installation time and probably also asking only after 10 minutes the app is used (or something like this).

What do you think @mhutti1 @EladKeyshawn @rashiq @rgaudin ?

**Comment by mhutti1** [comment]
@rashiq Suggested the timing that we currently have. I would personally prefer it to appear a bit later but apparently research is on the side of showing it early. It has certainly got us good reviews.

**Comment by rgaudin** [comment]
I believe a better approach would be to mix several information like the
number of openings (lot of users might open it to find a specific info and
close), the delay of course and maybe the actions taken but that's a lot
more intrusive.
I know some apps trigger it on great features that are beyond just opening
to ensure it happens at a positive moment. As most, I hate it when I'm
asked to rate before having even been given a chance to use it.

One thing I'd like to specifically suggest is that we don't trigger the
dialog if there's no active internet connection as it's highly improbable
that someone would activate Internet (if possible) just to rate the app

Let's just not forget that rating the app if still a burden for users and
they are only doing us a favor by doing so.

**Comment by automactic** [comment]
In iOS, I do it like this:

Please rate alert will be displayed only when:
1. App is 7 days old since first launch
2. App has more than 10 active session (sessions where app stay on screen for more than 10 seconds)
3. when people enter preference screen
4. have not rate app before

In Please rate alert, I give people 3 options:
- Rate now, which takes people to kiwi's app store page, and mark the app as rated
- Rate later, which reset the 10 active use history, also reset the 7 day count
- Never remind me again, which marks the app as rated

**Comment by kelson42** [comment]
@automactic Thx that's interesting
I think the option of not asking if app is not online like @rgaudin said seems to me to be important in all cases.

**Comment by kelson42** [comment]
@EladKeyshawn May you please (first) avoid any display of the dialog if not internet connection is available?

**Comment by EladKeyshawn** [comment]
@kelson42 Yes I'm on it

**Comment by kelson42** [comment]
@EladKeyshawn  Thx.

**Comment by mhutti1** [comment]
@EladKeyshawn Slight permission issue with custom apps but I think I fixed it 699416a09dfb5d4c59883459f1f64f1ca3bdde55

**Comment by kelson42** [comment]
I close that ticket as I think the most important problem has been fixed and their is no consensus about the best approach for the rest of the topic. Feel free to re-open it if you have additional material for the discussion.
