### ISSUE TITLE
Android Bookmarks should save the ZIM metadata "name" (if available)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#305]
I have implemented last WE the support of the ZIM metadata "name". The name being a string which is table over ZIM revisions. Using it should allow to keep the bookmarks even after a ZIM file update. If available this name should be taken instead of the ZIM file name (or UUIS, not sure what is use currently). For now, I do not have published officially ZIM files with this metadata, but I have provided a demo file which can be used for dev purposes here: http://tmp.kiwix.org/zim%2bftindex/wikipedia_bm_all_nopic_2016-09.zim.

**Comment by kelson42** [comment]
@EladKeyshawn The first ZIM files with this new tags have been created and in library.xml.

**Comment by EladKeyshawn** [comment]
@kelson42 In the code the bookmark entity contains "ZIM id" not "name", I guess its the same meaning.
but just confirming that with you.

**Comment by kelson42** [comment]
@EladKeyshawn no the ZIM id is a unique identifier for a ZIM file, the ZIM name is permanent over revisions of the file http://www.openzim.org/wiki/Metadata.

**Comment by EladKeyshawn** [comment]
@kelson42  Yeah, first of all in the page you sent there name and title, did not see any id. But of course, there should be a unique id per zim. Anyways I need to know if all zim files now provide a name?

**Comment by kelson42** [comment]
@EladKeyshawn no, do not assume they will, use the current solution as a fallback.

**Comment by mhutti1** [comment]
@EladKeyshawn Be sure to checkout ade6aed3623381a8a1d410b7b314c34a812b0080 for any conflicts. I don't think there would be but better safe than sorry.

**Comment by mhutti1** [comment]
Part 1:
Steps to reproduce:
1. Download a ZIM file through our app.
2. Bookmark a page.

What you get:
- We save bookmarks based on ZIM file ID. 

What we want:
- The possibilty fo saving/retrieving bookmarks by ZIM name.

This should be achived by:
- Functions in https://github.com/kiwix/kiwix/blob/master/android/src/org/kiwix/kiwixmobile/database/BookmarksDao.java that can save, delete, ... bookmarks by ZIM name as well as the current ZIM ID.
- A new field in https://github.com/kiwix/kiwix/blob/master/android/src/org/kiwix/kiwixmobile/database/entity/BookmarksSpec.java to save the zimName.
- Increment the database version and add code to add the new column for the version upgrade as specfied here https://github.com/yahoo/squidb/wiki/Implementing-database-upgrades. To this file  https://github.com/kiwix/kiwix/blob/55f70d22a85dc5a114e056549af31d42f527da49/android/src/org/kiwix/kiwixmobile/database/KiwixDatabase.java
