### ISSUE TITLE
url for library.xml

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-xulrunner#308]
the old url http://www.kiwix.org/library.xml now gives a 403 error when opening in python with urllib2.urlopen.

http://mirror3.kiwix.org/library/library.xml works, but seems a little ad hoc.

what url should I use?

**Comment by automactic** [comment]
I am using https://download.kiwix.org/library/library.xml in the iOS app. But this one seems to redirect to http://mirror3.kiwix.org/library/library.xml

**Comment by kelson42** [comment]
@tim-moody Problem is fixed. This is a redirect now (HTTP 301). We had to do this because of the release of our new web site. The new official URL is https://download.kiwix.org/library/libary.xml

**Comment by tim-moody** [comment]
yes.  it now works, but please note that you have a typo in the url above (S.B. library not libary)
