### ISSUE TITLE
Android library XML url should be updated

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#309]
It's currentl http://www.kiwix.org/library.xml
and it should https://download.kiwix.org/library/library.xml

The old one should still work, but we slowly become deprecated.

**Comment by mhutti1** [comment]
This is proving to be tricky. I don't think retrofit likes the redirect :(

**Comment by mhutti1** [comment]
It seems as well as the redirect issue the way we currently handle the XML fails if the schema is not what it is expecting. It was not expecting the fields name and tags. This was what was causing retrofit to crash and the no network error to appear.

**Comment by mhutti1** [comment]
@kelson42 As a warning I just one to say that editing the formatting of the download XML or adding attributes could cause the app to be unable to access downloads in the future and as such from this point onward we would need to come up with some solution to this.

**Comment by kelson42** [comment]
@mhutti1 this is a problem if we can not add fields without breaking the android app. Any chance to get rid of this problem?

**Comment by mhutti1** [comment]
I will try but it might be an issue with the library we are using.
Hopefully I might be able to at least give the user a more helpful error
message.
