### ISSUE TITLE
Make download manager more resilient to server-side XML changes.

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#311]
Currently adding fields to the XML will cause the app to fail with a no network connection error.

**Comment by kelson42** [comment]
I support this.

Here is the list of attibutes/metadata we want to implement piece by piece in the ZIM metadata and in the catalog:http://wiki.kiwix.org/wiki/Catalog

Even if in 2017 we finally move to the OPDS format, we need the flexibility of adding new attibutes/properties.

**Comment by kelson42** [comment]
@mhutti1 Any chance to fix this? So we can go ahead on new fields/attributes in 2017?

**Comment by mhutti1** [comment]
@kelson42 This should be fixed. I have tested with my own website. I would however advice that once new XML fields are added we check for certain the app works fine.

**Comment by kelson42** [comment]
@mhutti1 Really great. Thank you!
