### ISSUE TITLE
ZIM files can't manually be opened from some file managers

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#313]

**Comment by mhutti1** [comment]
Some file managers can see the file association but some such as the default in 6.0 upwards can't.

**Comment by kelson42** [comment]
Yes I confirm this from a personal point-of-view and also I hear about that problem time to time with user feedbacks.

**Comment by mhutti1** [comment]
Steps to reproduce:
1. Download a ZIM file through our app.
2. Attempt to open local file in a file manager.

What you get:
- In the majority of file managers this fails (e.g android 7.0 default settings file manager).

What we want:
- ZIM file opens in our app for (all if not most) file managers.

**Comment by mhutti1** [comment]
So the problem is that android can't associate files by extension only by mime type. But android also doesn't really support mime types. This leads us to have to use application/octet-stream as a general mime type meaning our app might try to open some unrelated files if the user clicks on them. I think that this is a decent albeit annoying compromise for now.

**Comment by kelson42** [comment]
Test on a Andorid 6.0.1 device (Samsung):
* OI File Manager (works fine, after providing a choice of apps to use)
* Default "My Files" app (does not work "Unable to find application to perform this action")
* ES File Explorer (does not work, propose first to identify the type of the content [text, audio, video, ...] and then propose a list of app for each type - Kiwix is nowhere)

Test on a Android 4.2.2 device (Samsung):
* Default "My Files" (Does not work "Unable to find application to perform this action")

So, it seems that the association with "application/octet-stream" even does not always work.

**Comment by mhutti1** [comment]
@kelson42 This is not good. I have a bad feeling Samsung may be the issue here making it either impossible or requiring an even more cumbersome workaround.

**Comment by mhutti1** [comment]
@kelson42 Try now.

**Comment by kelson42** [comment]
@mhutti1 THX a lot, I'll do it tomorrow.

**Comment by kelson42** [comment]
Works perfectly with all of my tests. Kudos!
