### ISSUE TITLE
Android Kiwix 2.00 on pre-release crashes displaying Help on Samsung S3

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-xulrunner#314]
I think this is a known issue and might have been fixed in the main branch. Nonetheless Emmanuel asked me to file a new issue so that we track the issue and make sure it's fixed before 2.00 goes mainstream.

`E/AndroidRuntime(31528): FATAL EXCEPTION: main
E/AndroidRuntime(31528): android.view.InflateException: Binary XML file line #60: Error inflating class Button
E/AndroidRuntime(31528):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
E/AndroidRuntime(31528):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
E/AndroidRuntime(31528):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
E/AndroidRuntime(31528):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
E/AndroidRuntime(31528):        at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
E/AndroidRuntime(31528):        at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
E/AndroidRuntime(31528):        at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
E/AndroidRuntime(31528):        at org.kiwix.kiwixmobile.KiwixMobileActivity$KiwixWebViewClient.onPageFinished(KiwixMobileActivity.java:1861)
E/AndroidRuntime(31528):        at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:416)
E/AndroidRuntime(31528):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31528):        at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(31528):        at android.app.ActivityThread.main(ActivityThread.java:5419)
E/AndroidRuntime(31528):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(31528):        at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(31528):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
E/AndroidRuntime(31528):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
E/AndroidRuntime(31528):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31528): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/get_content_ripple_shape.xml from drawable resource ID #0x7f02005c
E/AndroidRuntime(31528):        at android.content.res.Resources.loadDrawable(Resources.java:2974)
E/AndroidRuntime(31528):        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
E/AndroidRuntime(31528):        at android.view.View.<init>(View.java:3563)
E/AndroidRuntime(31528):        at android.widget.TextView.<init>(TextView.java:881)
E/AndroidRuntime(31528):        at android.widget.Button.<init>(Button.java:108)
E/AndroidRuntime(31528):        at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62)
E/AndroidRuntime(31528):        at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:58)
E/AndroidRuntime(31528):        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
E/AndroidRuntime(31528):        at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:1008)
E/AndroidRuntime(31528):        at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1067)
E/AndroidRuntime(31528):        at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
E/AndroidRuntime(31528):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
E/AndroidRuntime(31528):        ... 16 more
E/AndroidRuntime(31528): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag ripple
E/AndroidRuntime(31528):        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
E/AndroidRuntime(31528):        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:873)
E/AndroidRuntime(31528):        at android.content.res.Resources.loadDrawable(Resources.java:2970)
E/AndroidRuntime(31528):        ... 27 more
I/ActivityManager( 2358): Notify an ApplicationCrash`

My guess is this commit fixed the problem https://github.com/kiwix/kiwix/commit/b66c7554bc55f1914f11e528ca05b8c6bf8c74d2 but I don't know if the pre-release of the Android app has been updated in Google Play since then.

The bug affected several devices running Android 4.x However several of my test devices were stolen (around 6 :( so it's a bit hard for me to retest the issue or fixes on many devices - however I can use the S3 which is running Android 4.3

I'm happy to test a fixed/updated apk file. My main laptops were also stolen and I've yet to have time to setup a new build environment :(

**Comment by mhutti1** [comment]
@julianharty Yes this should have been fixed in the main branch and now the latest beta build should have this fix. It might take a while to roll out as an update though. Can you comment to confirm that it works once you have tested the new beta APK.

**Comment by julianharty** [comment]
Will do, I've just downloaded it on a couple of devices, including the S3
and it hasn't crashed yet. Thank you Issac for fixing the problem.
