### ISSUE TITLE
Can not find ZIM files on external storage

### ISSUE THREAD

**Issue by morloy** [kiwix/kiwix-xulrunner#320]
I am still trying to load my ZIM files from the SD card. However, when I click on 'Get Content' I only see the ZIM files on internal storage.

To test this, I downloaded the 'Uganda' wiki to the internal storage and the 'Ray Charles' wiki to the SD card by changing the 'Storage' in the settings.
But regardless of the 'Storage' setting, I can only select the 'Uganda' wiki. The 'Ray Charles' never shows up and is thus unusable. Same happens with the 'enwiki' that I downloaded on my computer and put into the Kiwix folder on my SD card manually.

**Comment by mhutti1** [comment]
@morloy Does this happen with latest build 34 rolled out today?

**Comment by morloy** [comment]
@mhutti1 Great, first time that I see my files on the SD  card with the new update :+1: 

The full-text index of the 'dewiki' (split ZIM) doesn't load, though. But I need to check, if the files are corrupted/correctly named.

**Comment by mhutti1** [comment]
@morloy Can you also check that the enwiki that was put manually there is visible?

**Comment by morloy** [comment]
@mhutti1 Yes, enwiki is visible as well.
