### ISSUE TITLE
Android Kiwix 2.00 Settings page reacts unexpectedly

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-xulrunner#322]
A user reported the settings in 2.00 have a mind of their own. In essence they're correct - the behaviour is unexpected. Tapping consistently on any of the settings activates and deactives other settings in an unusual pattern. So far I've tested on two device models  - a CAT S50 running Android 4.4.2 and a Nexus 7 2013 running 4.4.4.

Testing on additional devices and other Android versions will help scope the problem. I've emailed a brief video (19.8MB unedited) to Emmanuel. I'm happy to add it here if practical and/or email it to anyone on the project who'd like it.

**Comment by julianharty** [comment]
Added the video - zipped so I could upload it to github.
[VID_20160922_203800.mp4.zip](https://github.com/kiwix/kiwix/files/488224/VID_20160922_203800.mp4.zip)

**Comment by mhutti1** [comment]
Wow. Thats very weird. I have it happening to me on an emulator. Doesn't happen on newer os versions. Will look into now.

**Comment by julianharty** [comment]
Very good. Here's the review FYI "New update is unstable. The settings have mind of their own and sliders move as they please. Who ever work on this update managed to render the app to something awful, very near to a distinguished crap!" The app was awarded 1 star as one might expect. 
https://play.google.com/store/apps/details?id=org.kiwix.kiwixmobile&reviewId=Z3A6QU9xcFRPRVFlSTdmbUh1c00yRVBDRHE0Z09IcjFOSWxDeHRTUncyWERYcnJlNmlVZ3dwVWdZQzNJeTVvVU5VQl9vb0RTVDNobUFKV0ZTLTdxa2U1X29n

**Comment by mhutti1** [comment]
Found problem 2ebce235502b14545dab5ce0fd76067a6f5e09c5 switchpreference is bugged in android 4.x  I am creating fix now.
