### ISSUE TITLE
Can't delete certain local ZIM files

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#325]
Some ZIM files on the SD card are unable to be deleted due to a permission error. If this can be fixed it should be otherwise we should inform the user to use a file engagement app to complete the action.

**Comment by mhutti1** [comment]
Adding to this that a user reported being unable to delete a file manually added even with the standard Samsung file manager.

**Comment by mhutti1** [comment]
We need to find guaranteed reproduction steps for this.

**Comment by kelson42** [comment]
@mhutti1 can we not simply make a check against the file system if we have enough permissions? And display an error if not?

**Comment by mhutti1** [comment]
@kelson42 Yeah but I was hopping to put this as a GCI task but can't find reproduction steps.

**Comment by kelson42** [comment]
@mhutti1 Yes, that a real problem. I would recommend to close the ticket (at least as long as we do not have a clear repro-case).

**Comment by mhutti1** [comment]
@kelson42 Yeah I will think if I can come up with steps for a bit longer but idk.
