### ISSUE TITLE
On Android, duplicates in storage list

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#326]
"Settings" > "Storage" display many entries (odd)
    1. 3.8
    2. 3.78
    3. 3.8
    4. 53.7

The first 3 ones are duplicates, I can reproduce the problem on my device.
I guess this because a storage device has many mounting points!

An relatively smart should be able to identify the duplicates based on the the content of the directory.

**Comment by kelson42** [comment]
@mhutti1 Any change to fix this for next/last 2.0 build?

**Comment by mhutti1** [comment]
mhutti1/android-storage-devices@0f5b308

Should have fixed

**Comment by kelson42** [comment]
@mhutti1 Something seems still to be buggy. I have now 3 entries:
1 - 4.99GB
2 - 5.01GB
3 - 134.01GB

**Comment by mhutti1** [comment]
I think this is fixed in the majority of cases but there may be one or two that have slipped through the cracks. Implementing a simple check to validate non duplicate zim id's should fix this.

**Comment by mhutti1** [comment]
After some though the best/only practical way I can think of solving this is to create a file in each location with a location ID. Two locations are unique if they have no file in any of their parent hierarchy with the same ID.

**Comment by kelson42** [comment]
@mhutti1 What is a LocationID?

**Comment by mhutti1** [comment]
@kelson42 an arbitrary random number.

**Comment by kelson42** [comment]
@mhutti1 Not sure to fully understand what you mean... but looks like you know what you are doing ;)

**Comment by mhutti1** [comment]
@kelson42 This should be fixed now. The only time there should be duplicates is if one is private storage and in this case we tell the user this.

**Comment by kelson42** [comment]
OK, then let see users feedbacks :) THX
