### ISSUE TITLE
Custom apps should validate their expansion files and re-download if corrupt/missing

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#331]
https://developer.android.com/google/play/expansion-files.html#Downloading

This article suggests that we should implement Googles download library and create a simple UI to inform the user of our progress.

**Comment by kelson42** [comment]
@mhutti1 I support the idea. Can we go ahead on this?

**Comment by mhutti1** [comment]
So this either requires us implementing https://developer.android.com/google/play/licensing/index.html or using our own download method. We will need to work out which is the best option.

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#64
