### ISSUE TITLE
Add customapp json field specifying expansion version code

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#332]
Google Play supports uploading an app to use a previous expansion file. A json field should be added to specify which expansion version custom apps should use or left blank to indicate using the current version code. Then the app should look for the correct file by editing the FileUtils class to point to the correct expansion file.

**Comment by mhutti1** [comment]
0b6f57666e9c6e63f86eba523001de439012da0e

**Comment by mhutti1** [comment]
The original file must still be in content.zim otherwise there will be a file size mismatch and we will assume that the app is corrupt.

**Comment by kelson42** [comment]
@mhutti1 Thx. That said not sure to fully understand how that shoudl work, should I simply increment the "code_version" but not the "content_version" to get a new APK reusing already upload/available companion file?

**Comment by mhutti1** [comment]
@kelson42 
"content_version_code" is optional. If you don't include it then the app will use its "version_code" as its content_version_code. If you do include it though you can override this to allow you to select a previous ZIM as you expansion.
