### ISSUE TITLE
Rate dialog should use app icon (instead of Kiwix icon)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#34]
A few days ago, an icon was added by @EladKeyshawn to the "Rate the app" dialog. This usability improvment (more fancy UI) generates an awkward situation with "custom apps" like Wikivoyage or Wikimed. The users of these last two apps do not know about Kiwix and will therefore be surprised to see its logo at this place because the "rate me" dialog is not only displayed for the Kiwix app but for all apps (which is really good). This "static" Kiwix icon shoulw be probably replaced by a dynamic solution (always working), for example it would be a benefit tout simply display in place the app logo.

**Comment by EladKeyshawn** [comment]
@kelson42 I skimmed through the code the script should just change the value of kiwix.png so the expected result is the icon changed. I have not tested this yet though.

**Comment by kelson42** [comment]
Great :) Thank you. I'll test it next week after vacation.
