### ISSUE TITLE
Duplicate entries in "local" tab on Android content manager

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#344]
In my case many files appears twice. @mhutti1 Any change to fix this for next/last 2.0 build?

**Comment by mhutti1** [comment]
Related to #326. Will try to fix now

**Comment by mhutti1** [comment]
https://github.com/mhutti1/android-storage-devices/commit/0f5b308f0b088c43b0175a8c1e449dc053f1b8c1

Should have fixed

**Comment by kelson42** [comment]
Looks good to me. :+1:
