### ISSUE TITLE
Should copy-on-write be disabled when using kiwix-index and btrfs?

### ISSUE THREAD

**Issue by ghost** [kiwix/kiwix-xulrunner#345]
I'd like to index my zim files with `kiwix-index` but it seems to take an enormous amount of time while slowing my system considerably. I wonder if that may depend on the fact that I'm using the btrfs filesystem. Is disabling the btrfs copy-on-write feature for the directory with the zim files needed? My zim files are stored in `~/Kiwix`, so I may need to run the following command:

```
chattr +C ~/Kiwix
```

Did anybody else experience a similar problem?

I'm making some tests right now, but it will take a while. I'm going to leave a feedback later.

**Comment by kelson42** [comment]
kiwix-index is slow yes, I do not think this is problem with btrfs.

**Comment by kelson42** [comment]
Better us the indexes with already provide

**Comment by ghost** [comment]
Unfortunately I didn't find any obvious difference between enabling/disabling copy-on-write for the directory containing zim files. I'm probably going to accept your suggestion and use the indexes you already provide. Thanks.
