### ISSUE TITLE
Native crashes in latest build of kiwix

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#346]
I have reverted the version to fix the crashes but we will need to investigate the root cause.

**Comment by kelson42** [comment]
Awesome, I was pretty worried to see all one-stared feedback this morning. Thx you for quick fix an release of build 41

**Comment by mhutti1** [comment]
@kelson42 I don't think its worked. It looks like the problem now might be xamian related.

Revision: '0'
ABI: 'arm64'
pid: 21390, tid: 21390, name: wix.kiwixmobile  >>> org.kiwix.kiwixmobile <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0   0000000000000000  x1   000000000000538e  x2   0000000000000006  x3   0000000000000000
    x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
    x8   0000000000000083  x9   0000007f85225158  x10  0000000000000001  x11  0101010101010101
    x12  0000000000000028  x13  0000000000000000  x14  0000000000000001  x15  0000007f84e08000
    x16  0000007f84e08568  x17  0000007f84d9a3cc  x18  0000007f84e19f50  x19  0000007f852250a8
    x20  0000007f85224fe8  x21  0000000000000002  x22  0000000000000006  x23  0000007f6b012000
    x24  0000007f80137300  x25  0000007fefddd5f8  x26  0000007fefddd600  x27  0000007f6aed3d18
    x28  0000007fefddd5e8  x29  0000007fefddd3d0  x30  0000007f84d97b68
    sp   0000007fefddd3d0  pc   0000007f84d9a3d4  pstate 0000000020000000

backtrace:
    #00 pc 00000000000693d4  /system/lib64/libc.so (tgkill+8)
    #01 pc 0000000000066b64  /system/lib64/libc.so (pthread_kill+68)
    #02 pc 0000000000023a38  /system/lib64/libc.so (raise+28)
    #03 pc 000000000001e1d8  /system/lib64/libc.so (abort+60)
    #04 pc 00000000004e6018  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (_ZN9__gnu_cxx27__verbose_terminate_handlerEv+396)
    #05 pc 000000000049538c  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (_ZN10__cxxabiv111__terminateEPFvvE+8)
    #06 pc 00000000004953f8  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (_ZSt9terminatev+12)
    #07 pc 0000000000495534  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (__cxa_throw+136)
    #08 pc 000000000036a31c  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so
    #09 pc 00000000003691e0  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (_ZN6Xapian8DatabaseC2ERKSsi+244)
    #10 pc 000000000014ec10  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (_ZN5kiwix14XapianSearcher9openIndexERKSs+496)
    #11 pc 000000000014e9b8  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (_ZN5kiwix14XapianSearcherC1ERKSs+136)
    #12 pc 0000000000149bec  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (Java_org_kiwix_kiwixmobile_JNIKiwix_loadFulltextIndex+156)
    #13 pc 0000000000bf38e8  /data/app/org.kiwix.kiwixmobile-1/oat/arm64/base.odex (offset 0x8ce000)

**Comment by mhutti1** [comment]
Found Issue. It occurs when attempting to access full text database of a split zim file. I can possibly fix on my end but I am not certain.

**Comment by kelson42** [comment]
@mhutti do you have a step-by-step procedure to reproduce the problem? Does that fails with all splitted ZIM files?

**Comment by mhutti1** [comment]
Yes as far as I know. Thinking about it I doubt I can fix myself. As such I
will have to revert zimlib and submit update unless we can fix today.

**Comment by kelson42** [comment]
I have a reprocase, give me one hour.

**Comment by kelson42** [comment]
@mhutti1 works better for you too?

**Comment by kelson42** [comment]
put I have again duplicates in my "local' tab

**Comment by mhutti1** [comment]
I am testing now. I reverted the fix for the duplicates thinking it caused the crash but it didn't so I have re added it and am testing your fix now.

**Comment by kelson42** [comment]
Fixed.
