### ISSUE TITLE
Fulltext Crash

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#349]
When using main Kiwix app to read wikimed en and enabling fulltext search I get this crash.

Build fingerprint: 'google/bullhead/bullhead:7.0/NBD90W/3239497:user/release-keys'
Revision: 'rev_1.0'
ABI: 'arm64'
pid: 28354, tid: 28872, name: Filter  >>> org.kiwix.kiwixmobile <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    x0   0000000000000000  x1   0000000000000001  x2   000000000000000f  x3   00000070ce61092c
    x4   0000000000000002  x5   000000000000fffd  x6   0000000000000000  x7   00000070ce61092c
    x8   00000070a40270b9  x9   fefeff6fa7bcff67  x10  7f7f7f7fffff7f7f  x11  0101010101010101
    x12  0000000000000008  x13  ffffffffffffffff  x14  ffffffff00000000  x15  ffffffffffffffff
    x16  00000070d21103b8  x17  00000070ed05c2e8  x18  00000070ec0b28b0  x19  00000070ce610a48
    x20  0000000072193000  x21  0000000012dd8100  x22  00000070f00b03f0  x23  0000000070e40fb0
    x24  0000000012e9ad80  x25  0000000012e01e38  x26  0000000012dd8100  x27  0000000012c5b2e0
    x28  0000000012c7eac0  x29  00000070ce610970  x30  00000070d19cb8ec
    sp   00000070ce610970  pc   00000070d19cb8f0  pstate 0000000060000000

backtrace:
    #00 pc 00000000001308f0  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (_ZN5kiwix13removeAccentsERKSs+112)
    #01 pc 0000000000122cd4  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (_ZN5kiwix8Searcher6searchERSsjjb+316)
    #02 pc 000000000011fa38  /data/app/org.kiwix.kiwixmobile-1/lib/arm64/libkiwix.so (Java_org_kiwix_kiwixmobile_JNIKiwix_indexedQuery+144)
    #03 pc 00000000007cb910  /data/app/org.kiwix.kiwixmobile-1/oat/arm64/base.odex (offset 0x751000)

**Comment by kelson42** [comment]
@mhutti1 I can not reproduce the problem with my two devices. Do you use last version published on the Play store?

**Comment by mhutti1** [comment]
@kelson42 its entirely possible my file could be corrupted. I will re download

**Comment by mhutti1** [comment]
@kelson42 You are right the newer version from wikimed crashes it I think but the current one in the online repository doesn't. This still might be an issue though if we update the list.

**Comment by kelson42** [comment]
@mhutti1 OK, I will have a look. How do you test it exactly (without using the play store).

**Comment by mhutti1** [comment]
@kelson42 I downloaded the ZIM file used in the wikimed en app from the internal download page and transferred that to my phone.

**Comment by kelson42** [comment]
@mhutti1 I have recompiled kiwix with git master head and test it with wikimed EN 2016-10. I have no crash :(

**Comment by kelson42** [comment]
@mhutti1 news on this? Where you able to reproduce the problem with a fresh install?

**Comment by mhutti1** [comment]
@kelson42 Yeah can confirm this is fixed in a fresh install.
