### ISSUE TITLE
Add 'While opening a new tab switch to it' option to Kiwix for Android

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#35]
In Kiwix for Android, while opening a page in new tab, focus goes to the newly opened page. Its a hindering to the flow of reading. There should be a check box option in the 'Settings' which asks 'While opening a new tab switch to it'

**Comment by EladKeyshawn** [comment]
@Kelson42 Do you mean on long press of hyperlink it should open the link in new tab and not switch to it? I think the user will be confused of what happened.

**Comment by kelson42** [comment]
I think we should just add the option in the settings. Per default it will work like now, but if the user want it, he can check the option in the settings and then it will open in background (but the dialog should still open).

**Comment by EladKeyshawn** [comment]
@Kelson42 exactly what i did...except i thought the open in background should be default, as that what i understood from your issue description.

**Comment by kelson42** [comment]
Per default the behaviour should not be changed I think, so switching to the new open tab is right (as long as the user does not change the settings).

**Comment by EladKeyshawn** [comment]
@kelson42  Yes. Done

**Comment by kelson42** [comment]
@EladKeyshawn Thank you :))) will test it and close the ticket. Please upgrade the CHANGELOG file.

**Comment by Akhilan** [comment]
@EladKeyshawn Thanks. I can help you both in testing. 
@kelson42

**Comment by EladKeyshawn** [comment]
@Akhilan Thanks you are welcome :smile:

**Comment by EladKeyshawn** [comment]
@kelson42  Can we close this ticket?

**Comment by kelson42** [comment]
This looks good to me, I have just made the necessary to make the app able to deal with UI translation.
