### ISSUE TITLE
Not reading properly from manually mounted  sdcard

### ISSUE THREAD

**Issue by putogithub** [kiwix/kiwix-xulrunner#350]
Hi ,i was testing version 2.0 and got some bugs . Then downgraded from official website to 
older version and it worked.  Anyway both of them cannot read zimXX on sdcard.
As i don't have an smartphone capable to read exFAT/NTFS , i forcibly mounted on **/storage/sdcard1**
and **/storage/sdcard0/Kiwix** (external sdcard has kiwix files)
Even that ESExplorer is OK reading zim files from that mount point(and i can watch movies ,etc)
kiwix as a real problem with this.
Obviously is Read-only system , but i don't understand what's the problem if
the main use of Kiwix are reading articles

**Comment by kelson42** [comment]
@putogithub What is the problem exactly? The file does not appear in Kiwix or it appears but then you can not read it? What happens if you use a file which is not in chunks?

**Comment by mhutti1** [comment]
@putogithub https://github.com/mhutti1/android-storage-devices/blob/master/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.java has a list of mount points that we check. /storage/sdcard0/ is not on there could you try mounting to one that is?

**Comment by putogithub** [comment]
Damn!
I can't believe it worked. I tried several , and , in the end **/storage/sdcard0/external_sdcard**
did the trick.
If someone ever tries Paragon SW(android) as I did , beware of pesky SELINUX permissions.
You have to set (on config) permissive to every option.And obviously , be able to
see the files on ESExplorer or any file explorer that you may have. 

I'm content and I think this issue is SOLVED , thank you @mhutti1

**Comment by kelson42** [comment]
@mhutti1 Would putting "/storage/sdcard0" in the list of scanned mount points have helped? Do @putogithub's paths are completly random or somehow standarts? Strange that "ESExplorer" can see them...

**Comment by mhutti1** [comment]
@kelson42 Yes it would help will add now so it is likely in the next release.
