### ISSUE TITLE
Allow persistent highlighting of text

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#351]
Allow the user to highlight important text to refer back to.

**Comment by kelson42** [comment]
@mhutti1 I saw a feedback about this feature... but I still do not get it. It's already possible to select/highlight text, so what is this feature request exactly about?

**Comment by mhutti1** [comment]
@kelson42 It means highlight in the form of annotations for future reference. ie yellow highlighter pen. Its not high priority and might be tricky to implement but it would be a good feature.

**Comment by kelson42** [comment]
@mhutti1 ok, I call this "annotating"

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#59
