### ISSUE TITLE
 Invisible/transparent menu on Android 

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#352]
On a few devices we have a problem. We have already a pretty long thread:
https://sourceforge.net/p/kiwix/bugs/930/?limit=25

**Comment by kelson42** [comment]
@mhutti1 A though?

**Comment by mhutti1** [comment]
@kelson42 I can attempt a fix but I don't have a device with the physical menu button and I don't think you can emulate it. Do you?

**Comment by kelson42** [comment]
@mhutti1 I can not reproduce the problem but we have a trusted user, would be great if you could put the APK to test somewhere online so we have him able to test it.

**Comment by kelson42** [comment]
@mhutti1 Good news, I can reproduce the problem on BitBar with a "Sony Xperia A Dogo Maki SO-04E"

**Comment by julianharty** [comment]
@kelson42 @mhutti1 FYI I've found at least one of my old collection of Android phones that has a sufficiently recent release of Android (4.0.4) and physical buttons, including the menu. I downloaded and installed both kiwix and the PHeT Simulations custom app and confirm I can reproduce the problem where the menu displayed by the app is virtually invisible when initiated by the physical menu key. It seems to be white(ish) text with a transparent background. It also appears at the bottom left; while the menu from the ... dropdown appears at the top right with black text on a white (solid) background. 

When the app is in night-mode the main background colour is black. The menu operated menu is somewhat easier to read - still white text on a transparent background, the drop-down menu is still black text on a white (solid) background.

Any reason why we can't set the background of the menu that appears for the menu button? Also can you send me an apk to test with and I can do some testing directly for/with you.

**Comment by mhutti1** [comment]
@julianharty That is ideally the solution. Once we have it working on the emulator I will send you an apk to test.

**Comment by mhutti1** [comment]
I can use <item name="android:itemBackground">@color/primary_light</item> to bring up a background but the text is white on white so we need to probably change its colour in code.
