### ISSUE TITLE
Add auto Day Night switch

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#354]
Automatically change from light to dark mode possibly utilising android's Day/Night theme. This should be an an additional option along with permanent night and permanent day.

**Comment by EladKeyshawn** [comment]
@mhutti1 I tried messing around with creating a custom theme for night-mode but there are specific elements that look horrible/hidden like the close(X) button in tabs which should be white now. You say there is built in function which takes care of all of that?

**Comment by mhutti1** [comment]
@EladKeyshawn I think to fix it we would need to change the colour to a predefined one in the style so that it auto updates if you get what I mean.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#58
