### ISSUE TITLE
"random article" icon does not appear consistently in portrait/landscape

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-xulrunner#356]
When starting kiwix for Android in landscape mode there is the "random" icon, while it does not appear when starting in portrait.

But if we start in portrait and tilt the screen, the icon remains with no particular room issue (however, if starting in portrait the icon does not appear when tilting to landscape).

Solution: have icon always appear or at least make sure it appears whenever tilting screen from portrait to landscape.

**Comment by kelson42** [comment]
@EladKeyshawn Thx for the quick reaction!

**Comment by EladKeyshawn** [comment]
@kelson42 No probs
