### ISSUE TITLE
External card invisible on Samsung Galaxy Tab GT-P5200 w/ 32GB sd

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#362]
On a Samsung Galaxy Tab GT-P5200 with an external SD card in it, a user reported that this external storage device is not visible in the settings as download location. He had only the tablet internal storage available in the list. As a consquence, he needed to use an external computer to download first the content (before transferring it to the table), which is a really not user friendly process.

He also told use that the mounting point of his SD card seems to be /storage/extSdCard/

Reported first on Twitter: https://twitter.com/iadzraku/status/798865796344778752

**Comment by mhutti1** [comment]
I guess the file system might be case sensitive. I can add the weird cased path and see if it helps the affected user.

**Comment by kelson42** [comment]
Android filesystem is ext(4) and is consequently case sensitive. So it is really important that all the possible paths are reviewed regarding that information.

**Comment by mhutti1** [comment]
43b8f9b54f29346dc82cd7d806d7d085272dbb18
