### ISSUE TITLE
.zim files from wikimedia newer than those provided by kiwix.org and inside the software.

### ISSUE THREAD

**Issue by khanhhung2512** [kiwix/kiwix-xulrunner#363]
I've just stumbled upon the following site https://dumps.wikimedia.your.org/other/kiwix/zim/wikipedia/ and found some .zim files even newer than those provided by kiwix.org and inside the software.

Example: wikipedia_en_all_2016-06.zim, wikipedia_en_medicine_2016-11.zim, etc.

My question is: Are they usable?

One more thing, where can I find the latest news of upcoming .zim files and software release? I heard that a new wikipedia_en_all.zim is about to be released.

Thanks.

**Comment by kelson42** [comment]
The master and what we distribute is at http://download.kiwix.org. https://dumps.wikimedia.your.org/ is only a mirror of it. That said we release time to time "wrong file", but most of the time we remove them quickly after remarking the error. This is the case here with wikipedia_en_all_2016-06.zim, but the mirror did not have removed it.
