### ISSUE TITLE
Replace "ZIM" by "Content" in a few places

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#367]
Now that we have a nice content manager I think we should tend to "mask" a little bit the terminology around the ZIM file format. The reason is that this might not be obvious at all for people to understand what is meant.

**Comment by mhutti1** [comment]
@kelson42 Sounds good.

**Comment by mhutti1** [comment]
2a03eb84edb9a36ce3af64d1e699b01fec89a75e
