### ISSUE TITLE
Improve Android "content manger" tabs

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#368]
To improve the usability, I propose to:
* distribute the 3 tabs over the whole width of the screen
* put "downloads" in the middle (between "local" and "remote")

**Comment by mhutti1** [comment]
@kelson42 
Firstly what do you mean by distributing that tabs? Are they not already distributed
As for moving the downloads I disagree. In terms of minimising swipes the most common movements are surely local -> remote (to see what to download) followed by remote -> local (switching back) the download tab is nether meant to be assessed via a swipe only by clicking the notification or by automatically moving there when you click download.

**Comment by kelson42** [comment]
@mhutti1 Something like the 3 tabs of the Twitter apps.

**Comment by mhutti1** [comment]
@kelson42 Is this tablet specific?

**Comment by kelson42** [comment]
@mhutti1 Not sure, I do not really have a phone for testing... but it might be that this mostly impacts the tablet UI (which has a really larger screen). Do you need a screenshot?

**Comment by mhutti1** [comment]
@kelson42 No I have been able to reproduce on bitbar I will look into this.

**Comment by mhutti1** [comment]
@kelson42 The tabs now fill up the page. Do you still think that its a good idea to swap remote and downloads (if so why)?

**Comment by kelson42** [comment]
Thx, I will check your patch. For the rest, I assume that if we do not have a consensus then keep it like it is.

**Comment by kelson42** [comment]
Tested, looks nice now on my tablet. Thx :)
