### ISSUE TITLE
Split Android code from that repo

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#369]
And create a dedicated git repo. The last blocker is tracked here https://github.com/kiwix/kiwix-lib/issues/1

**Comment by mhutti1** [comment]
@kelson42 Is it possible for us to do this: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/ so that we don't loose blame/history features that are really useful in development.

**Comment by kelson42** [comment]
@mhutti1 yes

**Comment by kelson42** [comment]
@mgautierfr has done it and it works with a new compilation stuff... We still need to fix during next hackathon with @mhutti1, how to deal with custom apps. Kudos!
