### ISSUE TITLE
Search box should be align on the right if UI uses a RTL language

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#370]
Currently it's alway aligned on the left.

**Comment by mhutti1** [comment]
@kelson42 Do you mean that the text should be typed right to left when searching?

**Comment by kelson42** [comment]
@mhutti1 the box itself should be on the right. But yes of course the text should be typed from right to the left (but this is maybe already the case).

**Comment by mhutti1** [comment]
@kelson42 For me the box is on the right I think? Are you talking about content search, online search or file search?

**Comment by kelson42** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1029718/20641437/f1378658-b3f7-11e6-8966-d30822019392.png)

**Comment by mhutti1** [comment]
![screenshot](https://lh3.googleusercontent.com/5DipVgDfmK8x8qSHHs_8zVOSD5LvdWw4DUpfHCyJDmh2L3GGChl-gyK_IzVe0rhwKCRyXvwmgie-=w557-h990-no)

**Comment by mhutti1** [comment]
It seems that long search bar can have the wrong text. But even short search bar when you type is the wrong way round.

**Comment by EladKeyshawn** [comment]
@mhutti1 On portrait the search box is aligned correctly, the problem is the box itself is not fully fit to the actionbar (it's at the middle).

**Comment by kelson42** [comment]
@EladKeyshawn yes, this is an other bug... and @mhutti1 also discovered that (with last wikimed ar) makeing landscape-portrait-landscape puts the whole set of buttons on the wrong side (right), it should be left like at the beginning.... Seems we have a little bit work to do around this ;)

**Comment by mhutti1** [comment]
http://www.phonearena.com/news/How-to-force-right-to-left-RTL-layouts-on-Android_id64154

This allows you to test in english.

**Comment by mhutti1** [comment]
@kelson42 We could potential make a few GCI tasks out of this each to fix a part of the RTL layout. Now we can reproduce easily enough it should be in a students capability,

**Comment by EladKeyshawn** [comment]
@kelson42 I have not encountered this yet ;)

**Comment by kelson42** [comment]
@mhutti1 Yes, split as much as you think this is necessary. Makes perfectly sense to me.

**Comment by EladKeyshawn** [comment]
@mhutti1 So you mean once the device is RTL and searching in LTR then I confirm its unaligned

**Comment by mhutti1** [comment]
@EladKeyshawn I can see 3 bugs at the moment. 

1. Search is LTR 100% of the time once you start typing. 
2. If the search bar is large enough it can show LTR initially.
3. If you switch orientation twice then you are reset to LTR.

**Comment by EladKeyshawn** [comment]
@mhutti1  For me when I set my device to Hebrew you can see when I type english it uses RTL. 
![screenshot 06-13 26 2016](https://cloud.githubusercontent.com/assets/17123769/20641621/741c018c-b404-11e6-9ca6-f50b78f13290.png)

**Comment by mhutti1** [comment]
@EladKeyshawn This doesn't happen for me. What device/os?

**Comment by EladKeyshawn** [comment]
@mhutti1 5.1 huawei mate s, but I checked on other apps like messanger and others and the behaviour is similar. So I dont think this is worth fixing.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#49
