### ISSUE TITLE
Rename Local and Remote in Android download menu

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-xulrunner#380]
We've had several notices that people actually do not understand the current wording - remote in particular seems to be the hardest to understand for people.
Suggested renames:
Local to "Available" (or downloaded, or local files)
Remote to  "Library" (or "Available content" if not used for the other one)

**Comment by kelson42** [comment]
An other proposition:
* Local to "Device"
* Remote to "Online"
* Download to "Downloading"

@mhutti1 I'm not sure about the propositions (which one is the best), but I agree on the problem.

**Comment by Popolechien** [comment]
Ah yes, even better  - I second Device, online and downloading.

**Comment by mhutti1** [comment]
I also agree and have changed them.

**Comment by kelson42** [comment]
@mhutti1 THX
