### ISSUE TITLE
Add Android 7.1.1 Circular icons

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#381]
We should implement circular icons for the main app and for the custom apps. I am not entirely sure how best to do this for custom apps @kelson42 do you have any ideas.

https://developer.android.com/about/versions/nougat/android-7.1.html?utm_campaign=android_launch_androidnougat_120516&utm_source=anddev&utm_medium=blog#circular-icons

**Comment by kelson42** [comment]
@mhutti1 Sounds relatively trivial!? For custom apps, each app round icon should indeed be created. They are all in their respective directories in the "custom" directory. Not sure how they are put in the "res", but that should be easy.

**Comment by mhutti1** [comment]
@kelson42 Currently we do this by python script calling a linux command. I don't know how it would work for a circle as it would require cropping in a weird way.

**Comment by EladKeyshawn** [comment]
@mhutti1 I think it could be done by an online service of which we can upload the icon with specific parameters and get the result. I'll look into it later.

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn Could someone of you do it for Kiwix, I would then do the necessary for custom apps (maybe create a new feature request if necessary).

**Comment by mhutti1** [comment]
@kelson42 I have added the assets for the Kiwix icon (not the code yet). The custom apps need just one icon with I think the highest resolution and then we can get the python script to create the different resolutions at build as we do at the moment.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#46
