### ISSUE TITLE
External SD card not detected on TREKSTOR SURFTAB XINTRON I IRDA

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#383]
Mount points are (given by "diskinfo" app):
* /mnt/media_rw/22E0-C711 (and?)
* /storage/22E0-C711

**Comment by kelson42** [comment]
Looks like that all sub-directories (not recursively) in /mn/media_rw/ can be considered like devices https://source.android.com/devices/storage/config-example.html

**Comment by mhutti1** [comment]
Yeah I will have to come up with some code to class all folders with xxxx-xxxx in it as potential devices.

**Comment by kelson42** [comment]
WORKS NOW :)
