### ISSUE TITLE
Compatibility issue with macOS Sierra 

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-xulrunner#388]
From the OTRS feedback system: "Since I upgraded to macOS Sierra Kiwix totally hangs up on start or opens in couple of minutes.  Moreover, every time I have to open .zim file of wikipedia again, it does not open last file automatically."

**Comment by kelson42** [comment]
I just have updated my OSX device, will have a look... but I guess that it should work, we have already tested with a user.

**Comment by oscu0** [comment]
Has there been any progress on this at all?

**Comment by Popolechien** [comment]
@antonshiryaev Not directly - we've started rebuilding the desktop app from scratch and won't invest into bug fixing, I understand.

**Comment by kelson42** [comment]
New Kiwix Desktop 2.0 for MacOS has been published in 2018 September. If you see it in iTunes, then this is good, otherwise you have to upgrade your MacOS. Sorry, supporting many old MacOS version costs too much resources. We won't do anything else here.
