### ISSUE TITLE
Interal Storage called "default"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#390]
Under certain conditions, in the Settings, it's written "STORAGE" > "Default". This should not happend, it should be "Internal" or "External (x)"

**Comment by kelson42** [comment]
Same in the message displayed if not enough space is available. The message is smart (it detect which alternate device might have enough place) - at least it looks like. Be in my example, it call this storage "default" instead of "Internal".

**Comment by mhutti1** [comment]
@kelson42 I don't understand your second message. As for the first message default is the name for the device before a user manually selects one. It should be possible to change this and I will look into it. It might require some time though.

**Comment by kelson42** [comment]
@mhutti1 I guess it will be fixed everywhere if you replace the "default" default label by the real device label.
