### ISSUE TITLE
SD card detection issue on Onyx i86HDML e-reader

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-xulrunner#391]
Copying OTRS feedback:
"The Kiwix Android app doesn't detect my device's microSD card (Onyx i86HDML e-reader with Android 4) from within the Settings menu. Trying to change the storage location only displays the internal storage of my device (it seems to locate the system partition and the user partition). The full path of the SD card is located at:

/extsd

I think that it might be a symlink from /mnt/extsd or something because both directories lead to the same location."

**Comment by mhutti1** [comment]
This will need to be added to the list of possible locations. I think that I will try to implement a solution where we can add more locations to the list remotely from a URL. @kelson42 Is there somewhere in the kiwix.org domain that we could store such a file?

**Comment by kelson42** [comment]
@mhutti1 can you try to put ASAP this new path to Kiwix (so in 2.1). Your idea is good IMO but we should try to handle this in a separate ticket. They are many considerations regarding such a system... probably hosting this no github directly is the best solution.
