### ISSUE TITLE
Update Gradle version and compilation scripts

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#392]

**Comment by kelson42** [comment]
Next week the kiwix-lib repo should be ready and I will create a branch to start to build against it (instead of ../src/dependences). If it works, we could then move the Android code to the kiwix-android dedicated git repo.

@mhutti Do you have other concerns/topic regarding the compilation?

**Comment by mhutti1** [comment]
@kelson42 No that should be good. I should be able to help make sure things are working right.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#42
