### ISSUE TITLE
Embedded ZIM doesn't work on Nexus 5X with 7.1.1

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#395]
It appears the /data/data/.../lib directory simply doesn't exist.

**Comment by kelson42** [comment]
@mhutti1 I'm not sure what is the status, but that seems to be an extremely important discover. This (kind of) problem might explain why a few people tells us the apps do not work at all. To you have a repro case? Do you have more details? Might that be possible to display a clear error message if this kind of problem occurs with an other path?

**Comment by mhutti1** [comment]
@kelson42 Yeah I can reproduce on my device. I also have done some research and it seems that we should add /data/app/.../lib as an alternative location as this is used on some devices. I will try to implement now.

**Comment by mhutti1** [comment]
I have now fixed for my device and hopefully for others.
