### ISSUE TITLE
Add context menu search to allow highlighted text to quickly be searched

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#398]
A user should be able to search a word by highlighting it and clicking "SEARCH KIWIX" as is currently achievable in the Wikipedia app. This should also work with custom apps as well.

![screenshot_20161223-151527](https://cloud.githubusercontent.com/assets/2286937/21456847/edf323ae-c922-11e6-9b98-abda28e50562.png)

**Comment by EladKeyshawn** [comment]
@mhutti1 I just noticed on the current context menu when you click the 3 dots for more, the menu background is white and the text can barely be seen.

**Comment by EladKeyshawn** [comment]
![screenshot_2016-12-23-17-51-19](https://cloud.githubusercontent.com/assets/17123769/21457520/a4114dcc-c938-11e6-9e75-b5d22cc502a4.png)

**Comment by mhutti1** [comment]
@EladKeyshawn Thats strange. It looks fine for me. What device / os again?

**Comment by EladKeyshawn** [comment]
Huawei Mate S, 5.1. I have a feeling it has something to do with my device specifically.

**Comment by mhutti1** [comment]
Yeah. I tested on another Huawei device and they had made a lot of changes from stock. I don't know if there's anything that we can do about this.

**Comment by kelson42** [comment]
@mhutti1 What is the difference between "Search Wikipedia" and "Search Kiwix" ?

**Comment by kelson42** [comment]
@EladKeyshawn @mhutti1 What is the status of the problem with Huawei?

**Comment by mhutti1** [comment]
@kelson42 moved to new issue as unrelated to this. #415
