### ISSUE TITLE
Kiwix search history should avoid duplicates

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#40]
Steps to reproduces:
1 - Make a search (and open) on "article 3"
2 - Make a search (and open) on "article 2"
3 - Make a search (and open) on "article 1"
4 - Make a search (and open) on "article 1"
5 - Open the search dialog and type nothing

You get:
A list of suggestions with this order "article3 article2 article1 article1¨ 

You should get:
A list of suggestions with this order "article3 article2 article1"

Remark:
Probably a small system to avoid duplicates in the list should be done. I would do it that way at each new search (open article) done:
1 - Add the last search to the search history (at the top) like currently.
2 - Remove any further duplicate in the rest of the list/history

**Comment by EladKeyshawn** [comment]
@kelson42 I just checked and i cant see the problem. That is something that i took care of early on.

**Comment by kelson42** [comment]
@EladKeyshawn so you confirm that if you make 5 search/open of the same article. The search history which is displayed at the time you click on the action bar only list one time this article?

**Comment by EladKeyshawn** [comment]
@kelson42 yap

**Comment by EladKeyshawn** [comment]
The problem that i've encountered after this is if you searched for article 1 and then article 2 and then again 1 the article 1 wont appear first in the list. which means its not exactly the last search.

**Comment by EladKeyshawn** [comment]
So @kelson42 have you tested this issue?

**Comment by kelson42** [comment]
@EladKeyshawn I confirm that I can not reproduce the problem but yes what you have reported is true. In that case the search should be put on the top of the list. Can you do that?

**Comment by EladKeyshawn** [comment]
@Kelson42 Yes i will.

**Comment by kelson42** [comment]
Great. Thx!
