### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#400]
I'd like to refactor the KiwixMobileActivity. I'm going to track all changes here. I'd also like to eliminate all strong View references that we have to get rid of all the memory leaks. 

- [x] Convert ListView to RecyclerView
- [x] Refactor out all private classes out of the KiwixMobileActivity

Will update the list as I go.

**Comment by kelson42** [comment]
@rashiq What is the status on this?

**Comment by rashiq** [comment]
@kelson42 I already pushed quite a few commits, but I'm still at it

**Comment by kelson42** [comment]
@rashiq What is the status on this? Could we close this ticket?

**Comment by kelson42** [comment]
@rashiq Looks like it makes only 2 years we have properly split Kiwix Desktop from Kiwix Android code base... I have the feeling this was far far away. Anyway I close this ticket as Kiwix Android has its own repo meanwhile.
