### ISSUE TITLE
Make it impossible to download twice a content on Android

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#403]
Steps:
* Open the "online" library
* Click on a content to download
* Comme back to the "online" library
* Click a second time on the same content

What we get:
* Content is still in the 'online' library
* Two downloads of the same content run in parallel

What we want:
* Content is removed from the 'online' library at the time the download start
* User is moved to the 'downloading' tab
* It's impossible to download twice a same content

**Comment by mhutti1** [comment]
@kelson42 I am struggling to reproduce this.

**Comment by EladKeyshawn** [comment]
@mhutti1 Are you on this ? I don't want to work twice 😉

**Comment by mhutti1** [comment]
@EladKeyshawn I can't reproduce it so Im not working on it.

**Comment by EladKeyshawn** [comment]
@mhutti1 really ? this is actually a bug that should occur on every device.

**Comment by mhutti1** [comment]
@EladKeyshawn Yeah I fixed it on my device and the emulator I have. So I thought I fixed it fully,

**Comment by EladKeyshawn** [comment]
@mhutti1 No need I fixed it. now pushing

**Comment by kelson42** [comment]
@EladKeyshawn Seems to perfectly works now :)

**Comment by kelson42** [comment]
@EladKeyshawn @mhutti1 This bug has re-appeared.

**Comment by EladKeyshawn** [comment]
Can you give me a specific Zim file with which it happens?

**Comment by kelson42** [comment]
@EladKeyshawn I mostly test with both Wikimed (English) files

**Comment by EladKeyshawn** [comment]
Generally even without my patch the downloading files should no longer
appear in the first place. So we I think it has to do with the most unique
parameter separating those files. I took the full name of the Zim file.
Maybe there are duplicates?

**Comment by kelson42** [comment]
@EladKeyshawn ZIM file should be identified by there UID, not by there title or filename

**Comment by EladKeyshawn** [comment]
Yes but I'm not sure we save that in the DB I need to check

**Comment by mhutti1** [comment]
@kelson42 Can you give a more specific reproduction case for this?

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn If I try to download quickly the two Wikimed (in English) ZIM files, only one disappear from the "online" tab. Even by trying to download the "bollywood" file, it often does not disappear from the "online" tab.

**Comment by mhutti1** [comment]
@kelson42 How about now?

**Comment by kelson42** [comment]
@mhutti1 Looks good now :)
