### ISSUE TITLE
Improve Google Play update script to allow updates without content change

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#407]
upload-apk.py should be updated to allow for uploading APKs with an existing expansion. For now this operation can only be achieved using the Google Play Admin Web UI.

**Comment by mhutti1** [comment]
@kelson42 as this requires an API key to test its not really suitable for GCI.

**Comment by kelson42** [comment]
@mhutti1 AFAIK update-play-store.py is only there to update the play store meta data, not to upload APK. So it is not clear to me which problem this ticket should solve.

**Comment by mhutti1** [comment]
@kelson42 my mistake I meant upload-apk.py

**Comment by kelson42** [comment]
@mhutti1 You mean, you meant update-play-store.py?

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android-custom#67
