### ISSUE TITLE
Allow custom app version_code to be unspecified and to instead query Google Play and increment

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#408]
If the version code is unspecified (not available or empty string) in a custom apps json we should query Google play and increment the version code from the latest version that is published (including alpha/beta).

**Comment by kelson42** [comment]
This is one of the few mandatory things to do to allow to build an auto-update system for custom apps. Important ticket.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#36
