### ISSUE TITLE
TTS feature totally disapeared from action menu (in git master)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#411]
@rashiq @EladKeyshawn @mhutti1 Any idea?

**Comment by EladKeyshawn** [comment]
@kelson42 Yeah, yesterday I had it too, I though it occurred only to me. after clearing data it came back.

**Comment by kelson42** [comment]
@EladKeyshawn What do you mean with "clearing data"? I do not think we can ask our users to do so? What is the trigger for this disappearance?

**Comment by EladKeyshawn** [comment]
@kelson42 I still don't know of course this is not something we should ask users, I just tried to see if it temporarily solves the problem. P.S after the TTS came back I also had issues with it like there was no stop option or after I clicked stop it kept playing.

**Comment by EladKeyshawn** [comment]
There were changes lately that might have caused this.

**Comment by kelson42** [comment]
OK, this is important we identify the problem. We have currently people complaining about the TTS system and I can not test it at all ;(

**Comment by mhutti1** [comment]
I should have fixed the button issue (another android lifecycle issue). @EladKeyshawn If you can reproduce the other issues and they havn't been fixed can you open another issue.

**Comment by kelson42** [comment]
@EladKeyshawn @mhutti1 For me everything works fine back, so @EladKeyshawn we need you to tell us if the pause/stop buttons works fine.

**Comment by LFT09KA** [comment]
kelson42 what is your build number  ?

**Comment by LFT09KA** [comment]
http://www.retro11.de/ouxr/u7ed/usr/src/cmd/uucp/cico.c.html

**Comment by LFT09KA** [comment]
414 vc as #2002201 because androis bug in majestick kernel

**Comment by LFT09KA** [comment]
kernel version 11 cyanogene build

**Comment by LFT09KA** [comment]
tty vs tts

**Comment by LFT09KA** [comment]
tty =ttytt.021(funk-action#__repeater.vcx*/!A!2041-y.7ub-A-_-PHY_&?%)

**Comment by LFT09KA** [comment]
y=mn x=nsa -rtls-94.py

**Comment by EladKeyshawn** [comment]
@kelson42 @mhutti1  I'm still experiencing the problem.
Reproduction:
1) start TTS from menu
2) stop TTS also from menu
TTS keeps running and is unstoppable.

Tell me if this occurs only on my device.

**Comment by mhutti1** [comment]
@EladKeyshawn I can't reproduce on my phone. I can reproduce on emulator though.

**Comment by mhutti1** [comment]
@kelson42  @EladKeyshawn So the problem was that our UtteranceListener was not being reset on versions of android before 6.0. It seems .stop() resets it in 6.0+ but doesn't pre 6.0 I have simply added code to manually reset it and this fixes on my emulator.

**Comment by kelson42** [comment]
@EladKeyshawn @mhutti1 Nice together work :)

**Comment by EladKeyshawn** [comment]
👍
