### ISSUE TITLE
Integrate with Android Screen Search

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#414]
It should be possible to search in Kiwix content throught the Android Screeen Search
https://developer.android.com/guide/topics/search/index.html

**Comment by mhutti1** [comment]
@kelson42 I have given this a short look and while useful it seems impractical for 2 reasons:

1. It only works online...
2. It requires the website that you are searching to link to the app so it would require mediawiki support.

**Comment by kelson42** [comment]
@mhutti1 Offline, Google search can find my Skype contacts and other stuff... I do not think it works only online.

**Comment by mhutti1** [comment]
@kelson42 That is using a different method: Persional Content Indexing. We would need to give a compiled index to Google as in https://firebase.google.com/docs/app-indexing/android/personal-content its probably possible but I don't know if its feasible.

**Comment by kelson42** [comment]
@mhutti1 Persional Content Indexing does not seems adapted to what I want to do.... Or an app like Dailymotion seems to use this to store the whole history of navigation... migth be also a good idea - but that is another topic.

**Comment by mhutti1** [comment]
@kelson42 It might not be adapted to it but it looks like the only way to do it avoiding the need for internet and mediawiki support. As suggested we could just store bookmarks and history in the index. Then possibly give the option to go into settings and press an index button that then pulls every page from the JNI (If this is possible) and indexes them.

**Comment by kelson42** [comment]
@mhutti1 We can not do that for all pages because this will (1) take a long time (2) need a big amount of storage. So you confirm there is no way - to your knowledge - to search in the our ZIM files from the Google global search?

**Comment by mhutti1** [comment]
@kelson42 I have now read your web page fully and see your alternative solution. The page is old though so I am not sure if it still works, considering its not mentioned in any newer documentation. It might just work if we can add our content provider but I am not sure.

**Comment by kelson42** [comment]
@mhutti1 I have open #417 to give access to the history (is another feature request).

**Comment by mhutti1** [comment]
@kelson42 It seems I was right and this won't work for us as Google depreciated this 3 years ago.

https://android.googlesource.com/platform/packages/apps/QuickSearchBox/+/ecf356c15143ab0583c64682de16d94a57f7dd1c

http://stackoverflow.com/questions/20001979/global-search-not-working-as-expected-in-android-4-4

It makes sense. Google doesn't want apps slowing down search.
