### ISSUE TITLE
Android menu is unreadable on Huawei Mate S, 5.1.

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#415]
![a4114dcc-c938-11e6-9e75-b5d22cc502a4](https://cloud.githubusercontent.com/assets/2286937/21577172/0196170a-cf49-11e6-9a4b-a9b527f7386d.png)

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn What is the status on this? Who exactly can reproduce the problem with on of its test device?

**Comment by EladKeyshawn** [comment]
I still have it on my Huawei device

**Comment by kelson42** [comment]
@EladKeyshawn @mhutti1 What is the solution to fix that problem? Elad seems to be the only one able to reproduce the problem (I have tried hardly on BitBar to find a device with the same problem without success)

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#31
