### ISSUE TITLE
Android downloads should persist and resume when KiwixService is killed

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#418]
If device crashes or reboots download progress should save and resume.

**Comment by mhutti1** [comment]
This works for me now but we should test thoroughly as I have changed some of the core download logic.

**Comment by kelson42** [comment]
@mhutti1 will give a try. Thank you for the fix.

**Comment by kelson42** [comment]
@mhutti1 I have powered-off my device while downloading two content... and after restarging Kiwix they have disappeared of the "Downloading" tab. So it seems to me we still have a problem.

**Comment by mhutti1** [comment]
@kelson42 cool will investigate.

**Comment by mhutti1** [comment]
@kelson42 how about now?

**Comment by mhutti1** [comment]
@kelson42 Could you please test again when you get time as I think I have fixed your issue.

**Comment by kelson42** [comment]
@mhutti1 I think this part is fixed now. THX
