### ISSUE TITLE
TOC shortlinks seem to fail on few devices/with a few content

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#424]
User feedback: 

> On my galaxy Tab A, the table of contents are only able to show me what is contained in the topic being studied. But clicking on the
![img-20161229-wa0065](https://cloud.githubusercontent.com/assets/1029718/21606741/bfee2bc4-d1b1-11e6-887f-ab1991ff3689.jpg)
 outlined subtopics doesn't move the page to the intended location. My friend Dave, who is also using kiwiks on his device has the same experience.
>  
> What we would love to happen is that the table of contents should act as a link or shortcut to the stated locations on the given page.

**Comment by mhutti1** [comment]
So turns out not all ZIM files have id attributes set for headers. This was easy to fix though as we can just assign our own ids to id less headers when we parse the DOM.
