### ISSUE TITLE
Downloads arn't verifiable

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#426]
Currently if you start a download and then reboot. And then connect to a network with a login interface our app happily continues taking the bytes offered by this illegitimate servers redirection as part of the download. I can't see anything in the header that might distinguish the real and the fake server.  The only time you can tell is when you "finish" the download the file is invalid or simply the wrong size. Is there anyway that we can tell that what we are downloading is infact a ZIM file from the request header? I think it might be possible to check that the library is accessible and well formed but this still offers no guarantees about the actual ZIM file.
@kelson42 @rashiq @EladKeyshawn ?

**Comment by borisfba** [comment]
@mhutti1 According to [RFC 7233](https://tools.ietf.org/html/rfc7233), legitimate server should return 206 code for request with 'Range' header, while login interface should return 200.
So, maybe we can add something like this:
`
if (response.code() != 206)
    throw new Exception("Illegitimate server");
`
in [here](https://github.com/kiwix/kiwix/blob/master/android/src/org/kiwix/kiwixmobile/downloader/DownloadService.java#L285)

**Comment by mhutti1** [comment]
@borisfba Good Idea but the server i'm testing with returns 206 :(

**Comment by borisfba** [comment]
@mhutti1 :(
Also, we can request few bytes that we already have and then compare them and if they are equal then continue

**Comment by kelson42** [comment]
@mhutti1 one solution would bot to identify local ips and make a special handling...

**Comment by mhutti1** [comment]
@borisfba @kelson42 Both those suggestions would work.

I worked out we could also use:
``
client.newCall(new Request.Builder().url(chunk.getUrl()).build()).execute().body().contentLength() == chunk.getContentLength()
``
This requires a second http request though :(

**Comment by borisfba** [comment]
@mhutti1 Maybe, we can use:
`response.body().contentLength() == chunk.getContentLength() - downloaded`
to avoid second request?

**Comment by mhutti1** [comment]
@borisfba 👍 Thats a great idea. We also need to account for future chunks though so something like 
``
response.body().contentLength() ==  (chunk.getContentLength() - downloaded) % ChunkUtils.CHUNK_SIZE 
``
I think.
