### ISSUE TITLE
automatically search for alternative storage support if full

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-xulrunner#433]
We have a number of people not figuring out that they can set the save path in the option. A neat trick would be for kiwix to automatically search for additional external storage if the default is full (or even look upfront for additional storage and ask if new download should be made on the bigger one).

![screenshot_2017-01-06-14-31-17](https://cloud.githubusercontent.com/assets/21675885/21761712/19db3a6c-d655-11e6-96f6-d930105b053c.png)

**Comment by kelson42** [comment]
Yes, this seems to me to be pretty important. Many users seem to miss the settings storage device switcher.

**Comment by mhutti1** [comment]
I have added a snackbar that prompts the user if there is insufficient space and opens a dialog to select an alternative if they click open. @kelson42 I'm not to sure for the prompt. Currently "Storage device selector" what do you think?
![screenshot_20170126-222555](https://cloud.githubusercontent.com/assets/2286937/22353212/58cac4c0-e417-11e6-8493-1152fad9cb44.png)

**Comment by kelson42** [comment]
@mhutti1 Looks good to me (but did not tried it). Let's try this and see how this is welcome by users. Thx.
