### ISSUE TITLE
kiwix-0.9+wikipedia_en_medicine_2016-12.zip is corrupt

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-xulrunner#434]
when unzipping kiwix-0.9+wikipedia_en_medicine_2016-12.zip

I get

Archive:  /library/downloads/zims/kiwix-0.9+wikipedia_en_medicine_2016-12.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by kelson42** [comment]
Thank you for the feedback. I confirm. I have removed the corrupted file and improved toolchain to avoid problem by syncing files.
