### ISSUE TITLE
Increase widget logo size on Android

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#44]
The logo is too small, it should be like for the firefox widget.

**Comment by EladKeyshawn** [comment]
@kelson42  Kiwix logo is not round so I think too large logo would not look so good.
but take a look at this resized one to 32dp ,
![screenshot 12-43am jun 07 2016](https://cloud.githubusercontent.com/assets/17123769/15838941/587c4790-2c49-11e6-9b5c-e760dd18f8c4.png)
 I think its enough isn't it?

**Comment by kelson42** [comment]
I still think the logo is a bit too small....
