### ISSUE TITLE
Search problem - some results disappear as typing advances

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-xulrunner#442]
(from OTRS - the example was with Wikipedia in Spanish but I guess it applies to other languages)
"If I type "fortaleza de san car" it shows me one result when there should be two:
1. Fortaleza de San Carlos de la Cabaña.
2. Fortaleza de San Carlos de Perote.
It only shows Perote (the second one), when la Cabaña appears in the list if I were to type only "Fortaleza de". So basically the search console ignores the existence of an article it normally finds with less granularity.

See attached file as well"
[WIKI.pptx](https://github.com/kiwix/kiwix/files/710505/WIKI.pptx)

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#26
