### ISSUE TITLE
UI language change of Kiwix for Android UI should apply to HTML render widget language

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#444]
Like this we should be able, if the ZIM file is correctly configured, to adapt the content, depending of UI language. This is  in particular needed for the Phets custom app.

**Comment by kelson42** [comment]
@mhutti1 Does that make sense to you?

**Comment by mhutti1** [comment]
@kelson42 How would the alternative languages be stored in the ZIM file?

**Comment by kelson42** [comment]
@mhutti1 All languages are stored (maybe partly with json files, ...) in the ZIM, javascript (in the ZIM HTML content) would do the rest.

**Comment by mhutti1** [comment]
@kelson42 So we can call javascript functions or use different urls. Ideally if we use java-script though text shouldn't be displayed until the app tells it which language to use to avoid flickering,

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#25
