### ISSUE TITLE
Patch for making kiwix-serve compile

### ISSUE THREAD

**Issue by godane** [kiwix/kiwix-xulrunner#446]
This is a patch from kiwix-tools since it was fixed there:
http://pastebin.com/GxnuBmer

Without this compiling kiwix-serve will fail.

**Comment by kelson42** [comment]
@godane Which compiler (version) do you use? What are the errors you get?

**Comment by mgautierfr** [comment]
Thanks @godane  for this patch.

Can you create a PR ? (And ideally make a reference to kiwix/kiwix-tools@5cfbda12 in the commit message).

**Comment by godane** [comment]
@kelson42 I used the code from this repo. Full error i got is here: http://pastebin.com/eMa56dvk

@mgautierfr Yes thats where i got the patch. Sorry about that.

**Comment by kelson42** [comment]
@godane May you please make a merge request for your fix?

**Comment by kelson42** [comment]
@godane @mgautierfr I have fixed manually. @godane thx.
