### ISSUE TITLE
Can we do something to have the magnify-glass icon always at the same place

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#447]
I have already get a few people complaining about this (search icon not always at the same place) but I'm not sure if something can be done. here is the last one:

> Search icon changes its position every damn time this app starts. Take a look at your picture number 4 and 3. At startup, search icon is near the upper right corner. Then after a second it is near the center top. When I open this app, most of the time I will have to search the article I want read. But when I hit the search icon, I usually end up clicking the star icon because suddenly it is now occupying the previous search icon position.

**Comment by borisfba** [comment]
@kelson42 We can swap star and search icons

**Comment by mhutti1** [comment]
@borisfba @kelson42 I think the best solution is never hiding the bookmark icon. Instead adding some code that simply disables it on the welcome page (either changing its color or creating a toast if the user attempts to click it). This would greatly improve the uniformity of the app. @borisfba can you work on this?

**Comment by borisfba** [comment]
@mhutti1 Yes, I'll do it ASAP

**Comment by borisfba** [comment]
@mhutti1 Take a look

**Comment by mhutti1** [comment]
@borisfba Look good to me. Should please a lot of users.
