### ISSUE TITLE
Sync /android/res/values-* with translatewiki

### ISSUE THREAD

**Issue by tbertels** [kiwix/kiwix-xulrunner#449]
The translatable strings aren't all available on https://translatewiki.net/w/i.php?title=Special:Translate&group=kiwix

**Comment by kelson42** [comment]
Yes, we have a massive string delay/discrepency with translatewiki. This sounds really important that #385 is implemented to avoid this problem in the future and solve this ticket.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#24
