### ISSUE TITLE
Unable to open the list of Bookmarks

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#455]
Nothing happens if I make a long click on the star icon.

**Comment by mhutti1** [comment]
@kelson42 This was implemented in ece41dab94943dc80541578bd6e1b249ba83c740. @rashiq can you elaborate on why you think it is bad UX and suggest an alternative?

**Comment by kelson42** [comment]
@mhutti1 I just see that a new "Bookmarks" entry has been put to the menus. Maybe we can have both? Would you be able to just bring back the "long click" behaviour?

**Comment by rashiq** [comment]
For me this is an anti pattern, since no other app uses it. Therefore most users wouldn't even know it's there (since they are not used to trying out this gesture).

**Comment by kelson42** [comment]
@rashiq any disadvantage of having both (menu entry && long click)?

**Comment by rashiq** [comment]
Nope not that I could think of. We can add it back, I just thought it's not being used either way by anyone (due to the previously outlined nature of this being anti-pattern).

**Comment by mhutti1** [comment]
Ok. So I have re added but I do agree that we should rethink how users interact with bookmarks to be more intuitive.

**Comment by kelson42** [comment]
@mhutti1 thx
