### ISSUE TITLE
Icon tooltip font color is wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#459]
by clicking on the icon a tooltip appears explaining the purpose of the button. the font is in black. Considering the background of the tooltip is black or grey (depending the android version) I think it would be better to make white (or grey light).

**Comment by EladKeyshawn** [comment]
I also experienced this but I thought it's specifically happening on my
Huawei.on  what device did you get this?

**Comment by kelson42** [comment]
@EladKeyshawn on my both Samsung Galaxy tabs?

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#21
