### ISSUE TITLE
Content download progress bar is not updated if not downloading

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#461]
Which has for consequence that if you restart Kiwix with an ongoing download, the progress bar is empty at the beginning - as long as you do not download new data (even if you have already downloaded 50% for example).

**Comment by EladKeyshawn** [comment]
@kelson42 I cannot reproduce the problem, for me after app restart the progress bar is up to date.

**Comment by mhutti1** [comment]
I can reproduce fine. I will fix it for the release of 2.3.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#20
