### ISSUE TITLE
Index/TOC not clickable in https://gu.wikipedia.org/wiki/ and https://gu.wikisource.org/wiki/

### ISSUE THREAD

**Issue by cyberorg** [kiwix/kiwix-xulrunner#462]
The main page on these wikis has Gujarati alphabets, clicking on those show all the articles starting with that alphabet(like Special:Allpages/A)

https://gu.wikipedia.org/wiki/
https://gu.wikisource.org/wiki/

For example: https://gu.wikipedia.org/wiki/%E0%AA%B5%E0%AA%BF%E0%AA%B6%E0%AB%87%E0%AA%B7:%E0%AA%AC%E0%AA%A7%E0%AA%BE%E0%AA%82%E0%AA%AA%E0%AA%BE%E0%AA%A8%E0%AA%BE%E0%AA%82/%E0%AA%85

In Kiwix those alphabets do not open list of articles, there is no other way to see list of articles, so Gujarati wiki in Kiwix is not really in usable state, could those pages be activated?

**Comment by kelson42** [comment]
@cyberorg Thank you for reporting the problem. Unfortunately, there is nothing much we can do on our side to change this. Would you volunteer to make an offline dedicated homepage (as a custom page on WP and WS) as replacements to the online homepages? You would there be able to just put things like you want to make it useful for Kiwix users.

**Comment by cyberorg** [comment]
Thank you for looking into this, I wouldn't know where to start, see how xowa manages to do it, you can close this if it is not resolvable.

**Comment by kelson42** [comment]
@cyberorg You just need to create the page on gu.wikipedia.org and let me know the title. I do not know Xowa in detail, but Xowa is dedicated to Mediawiki content, Kiwix is not.

**Comment by cyberorg** [comment]
https://gu.wikipedia.org/wiki/મુખપૃષ્ઠ is the main page, if you see the page source the index is between <table> just above <div id="mainpage"></div>

Here is the html of the section: http://paste.ubuntu.com/24064068/ that is what we need clickable.

**Comment by kelson42** [comment]
@cyberorg I think we should simply remove that section, either by creating a dedicated page for offline or by applying a CSS "noprint"

**Comment by kelson42** [comment]
@cyberorg If the 'class="noprint" is added here https://gu.wikipedia.org/w/index.php?title=%E0%AA%A2%E0%AA%BE%E0%AA%82%E0%AA%9A%E0%AB%8B:Index&action=edit the list will also disappear (only in prints and in Kiwix)... but I do not have enough permission to do that.

**Comment by cyberorg** [comment]
Without that we don't have any thing to navigate the whole wiki by.

**Comment by kelson42** [comment]
@cyberorg just type in the search box what you want to find... it works basically like an alphabetical index anyway,

**Comment by cyberorg** [comment]
I can probably do that, but the idea is to let school children explore the wiki, without a page that lists every available pages there is no way for them to discover those pages except by accident and searching(requires knowing what they are looking for), also typing that alphabet on english keyboard is whole new skill they'll have to learn just to explore it.

As other links work hope this can also be be made to work?

**Comment by kelson42** [comment]
@cyberorg got your point... but this is not trivial to get this working really find, in particular we many kinds of different scripts. An other feature to discover things in the "random page" one.

**Comment by kelson42** [comment]
Superseeded by https://github.com/kiwix/kiwix-desktop/issues/42
