### ISSUE TITLE
SD card seems to not be detected on Huawei Honor 7 (lite)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#464]
I have tested on BitBar with Huawei Honor 7 lite and I see only only the internal storage... although it seems to be an external SD card.

We have also a feedback about it:
https://play.google.com/apps/publish/?account=9116215767541857492#ReviewDetailsPlace:p=org.kiwix.kiwixmobile&reviewid=gp:AOqpTOFfjVJY38c9TQBfw6AYSPYxSGGEV2blDfDsofSqxijIUARoyBFDu69E3JpHtQhKZ5UIIX_inVPZ1n5dXSs

**Comment by mhutti1** [comment]
Well the Honor 7 on Bitbar doesn't have an SD card in it so its not really possible to fix this without finding out the mount point.

**Comment by kelson42** [comment]
@mhutti1 OK, I have asked the user... but no feedback.
