### ISSUE TITLE
Last version of wiktionary_fr does not exist in repo

### ISSUE THREAD

**Issue by fheslouin** [kiwix/kiwix-xulrunner#468]
The last version referenced in [library.xml](http://mirror3.kiwix.org/library/library.xml) (2017-02-19 version) does not exist in http://download.kiwix.org/portable/wiktionary/

**Comment by kelson42** [comment]
@fheslouin I have changed a bit the algorithm which makes the assumption ZIM->ZIP wrong... you probably need to add a check

**Comment by kelson42** [comment]
This should be fixed now.
