### ISSUE TITLE
previous versions missing in library.xml

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-xulrunner#472]
sometimes previous versions that are still in downloads do not appear in library.xml

I speculate that this is when they are more than 2 months old, such as

http://download.kiwix.org/portable/wiktionary/kiwix-0.9+wiktionary_en_simple_all_2015-10.zip
http://download.kiwix.org/portable/wiktionary/kiwix-0.9+wiktionary_en_simple_all_2016-05.zip

**Comment by tim-moody** [comment]
If I search for wiktionary_en in https://ftp.nluug.nl/pub/kiwix/library/library.xml

I get the following in which I only see wiktionary_en_all from 2017-03 (and same nopic and 2 x simple)

<book id="a4722a6b-d820-61b1-db14-8cca7889bfb7" title="Wiktionary" name="kiwix.wiktionary_en_all" description="Definition from Wiktionary, the free dictionary" language="eng" creator="Wiktionary" publisher="Kiwix" ... faviconMimeType="image/png" date="2017-03-07" url="http://download.kiwix.org/zim/wiktionary/wiktionary_en_all_2017-03.zim.meta4" articleCount="5079498" mediaCount="49067" size="1704406"/>
<book id="c71fe010-c580-27a8-8bcd-c733cfc3d44a" title="Wiktionary" name="kiwix.wiktionary_en_all" tags="nopic" description="Definition from Wiktionary, the free dictionary" language="eng" creator="Wiktionary" publisher="Kiwix" ... faviconMimeType="image/png" date="2016-12-23" url="http://download.kiwix.org/zim/wiktionary/wiktionary_en_all_nopic_2016-12.zim.meta4" articleCount="5017809" mediaCount="29" size="1319765"/>
<book id="aac82467-cc68-2310-7930-8379c5ae90f3" title="Wiktionary" name="kiwix.wiktionary_en_simple_all" description="From Wiktionary" language="eng" creator="Wiktionary" publisher="Kiwix" ... faviconMimeType="image/png" date="2017-01-15" url="http://download.kiwix.org/zim/wiktionary/wiktionary_en_simple_all_2017-01.zim.meta4" articleCount="25092" mediaCount="3197" size="39073"/>
<book id="be0b28a8-8988-cc5d-0296-8a4e7e7c7816" title="Wiktionary" name="kiwix.wiktionary_en_simple_all" tags="nopic" description="From Wiktionary" language="eng" creator="Wiktionary" publisher="Kiwix" ... faviconMimeType="image/png" date="2017-01-15" url="http://download.kiwix.org/zim/wiktionary/wiktionary_en_simple_all_nopic_2017-01.zim.meta4" articleCount="25092" mediaCount="49" size="5860"/>

**Comment by kelson42** [comment]
Seems to be the same problem like #471. What is sure is that only one version of the file is available in library.xml. The most recent zim with portable ZIM in library.xml and the most recent zim (independently of the portable zip) in library_zim.xml.
