### ISSUE TITLE
not durable when relocated to external drive

### ISSUE THREAD

**Issue by ghost** [kiwix/kiwix-xulrunner#473]
I tried moving kiwix to a removable drive.

Kiwix essentially bricks itself when trying to list repos afterwards.

It's possible I'm just stupid, but if we could explain this process better, that would make working with an external (portable) kiwix installation dir a much better process.

Maybe the answer is better explanations, maybe the solution is a "migrate" function (for library data, or for the entire .kiwix folder), maybe the solution is a heal-button that resets all the woes, instead of me redownloading a clean install instead of my bricked one.

Ideas?

**Comment by kelson42** [comment]
@Thetoxicarcade That should work, can you please give us the step-by-step procedure to reproduce the problem? I suspect you use Linux? Can you explain what means exactly "bricks itself"?

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#34

**Comment by ghost** [comment]
1. download kiwix
2. run. installs to home dir.
3. change path.
4. move files to that path.
5. kiwix restarts, once.
6. further restarts means it cannot retrieve the libary, or download new library files.

**Comment by kelson42** [comment]
Do you use Linux? Which one?
