### ISSUE TITLE
Some of the latest wiktionary are in /zim/ and library.xml but not in /portable/

### ISSUE THREAD

**Issue by letompouce** [kiwix/kiwix-xulrunner#475]
In the `library.xml` file I can find that there's a `wiktionary_en` version from 2017-03-07, which can be found in the [/zim/](http://download.kiwix.org/zim/wiktionary/wiktionary_en_all_2017-03.zim) files, but not in the [/portable/](http://download.kiwix.org/portable/wiktionary/) ones.

**Comment by letompouce** [comment]
`wiktionary_fr_all` from 2017-02-19 is referenced in `library.xml` but its URL points at `/zim/wikipedia/wiktionary_fr_all_2017-02.zim.meta4` -- the bug here is the `/wikipedia/` directory.

The same goes for the `wiktionary_fr_nopic` version from 2017-02-25.

**Comment by kelson42** [comment]
Problem has been fixed that way:
* in library.xml, latest ZIM files with portable version
* in library_zim.xml, latest ZIM files whatever they have a portable version or not.
