### ISSUE TITLE
phet_en is in library.xml and /zim/ but not in /portable/

### ISSUE THREAD

**Issue by letompouce** [kiwix/kiwix-xulrunner#476]
`phet_en_all` from 2017-03-01 is referenced in `library.xml` and available from [/zim/](http://download.kiwix.org/zim/phet/phet_en_2017-03.zim) but not from [/portable](http://download.kiwix.org/portable/phet/).

**Comment by kelson42** [comment]
@letompouce This is on purpose. Phets files are so smalls and ft index does not make sense. Is that a real problem?

**Comment by kelson42** [comment]
The problem has been fixed, all ZIM files in libary.xml should now have (back) a portable version. (Newer) ZIM files without (or with) a corresponding portable file, can be found in library_zim.xml.
