### ISSUE TITLE
Kiwix fails when using an up to date libpng

### ISSUE THREAD

**Issue by Larivact** [kiwix/kiwix-xulrunner#477]
XULRunner uses [libpng](http://libpng.org/pub/png/libpng.html), which depends on [zlib](http://www.zlib.net/). You are shipping XULRunner without libpng
but with the old ZLIB_1.2.7.1, resulting in a conflict when you have an up to date version of libpng.

For example I am using Arch Linux with libpng `1.6.29-1` and when I try to run the Kiwix it fails:
```
$ ./kiwix
XPCOMGlueLoad error for file /home/larivact/kiwix/xulrunner/libxul.so:
/home/larivact/kiwix/xulrunner/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/libpng16.so.16)
Couldn't load XPCOM.
```

**Comment by stardiviner** [comment]
I have the same issue.

**Comment by stardiviner** [comment]
@Larivact Do you have a solution to manually fix this temporary?

**Comment by kelson42** [comment]
I suspect, we will have here to wait to Kiwix 2.0 for Desktop, unfortunately :(

**Comment by ghost** [comment]
I have the same issue too.

**Comment by PharmaceuticalCobweb** [comment]
I am also experiencing this same issue with Parabola GNU/Linux-libre (a derivative of Arch Linux). Currently using libpng version "1.6.30-1". I've had this issue since April too.

Missing Kiwix big time, I don't have an Internet connection very often.

**Comment by PharmaceuticalCobweb** [comment]
One of the latest comments on the unofficial AUR packages suggests running " sudo ln -sf /usr/lib/libz.so.1 /usr/lib/kiwix/xulrunner/libz.so.1 " as a workaround. I've tried it and it does appear to work.

Not sure if this might work with other distros but this seems to work with both Arch and Parabola.

**Comment by stardiviner** [comment]
@PharmaceuticalCobweb Thanks. it works.

**Comment by PharmaceuticalCobweb** [comment]
Glad to hear it, I've missed Kiwix so much. Make sure to thank "THS" in the comments on " https://aur.archlinux.org/packages/kiwix-bin/ ".

**Comment by kelson42** [comment]
We won't fix that bug as we develop already kiwix-desktop 2.0 to be release in summer 2018. People have to live with the workaround.
