### ISSUE TITLE
Kiwix for Windows freezes for some entries.

### ISSUE THREAD

**Issue by khanhhung2512** [kiwix/kiwix-xulrunner#479]
Entries such as "Eurasian Economic Union" and "Germany national football team" make the Kiwix on my laptop freeze. On my Android tablets, those entries take a lot of time to load, but they can still be loaded.
![eeu](https://cloud.githubusercontent.com/assets/23390760/25041785/a6fc947c-213c-11e7-976b-96ce8b03fec0.jpg)

**Comment by kelson42** [comment]
I suspect we will have to wait the release of Kiwix 2.0 for Desktop to get that fixed.

**Comment by kelson42** [comment]
This works fine with Kiwix Desktop 2.0
