### ISSUE TITLE
Migrate Search Database to Squidb

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#48]
Migrate the current "Recent Searches" database to [squidb](https://github.com/yahoo/squidb).
We've already started implementing squidb for the download manager, but it's not in use yet.
The current search database can be found in: [DatabaseHelper.java](https://github.com/kiwix/kiwix/blob/master/android/src/org/kiwix/kiwixmobile/utils/DatabaseHelper.java), and the new database implementation & the new database models can be found under the the /database/ package.

**Comment by Spacejoker** [comment]
I will take a look at this.

**Comment by mhutti1** [comment]
#57 Good Work :+1:
