### ISSUE TITLE
Problem with translations in Kiwix for Android

### ISSUE THREAD

**Issue by asereze** [kiwix/kiwix-xulrunner#482]
Every time I close and open Kiwix (2.2) again from my phone the language switches back from the one I choose to the system language (in my case, Italian). If I open the list of languages the one who's selected is the correct one, but I have to click on it again to change the language of the app.

**Comment by mgautierfr** [comment]
The android code has been moved to https://github.com/kiwix/kiwix-android repository.
I've opened your bug there (https://github.com/kiwix/kiwix-android/issues/109)

I'm closing this one. The bug will be handled on kiwix-android repository.
