### ISSUE TITLE
kiwix library 

### ISSUE THREAD

**Issue by amirh123123** [kiwix/kiwix-xulrunner#493]
kiwix library not work with my screan reader my screan reader is jaws thanks

**Comment by kelson42** [comment]
kiwix-xulrunner is not maintained anymore. So we won't implement this. Please wait a bit that we realease kiwix-desktop 2.0 and if this still do not work, report it https://github.com/kiwix/kiwix-desktop. But I suspect this might be complicated to fix as we do not have the device ourself.
