### ISSUE TITLE
index

### ISSUE THREAD

**Issue by amirh123123** [kiwix/kiwix-xulrunner#499]
hi i want 2 function for index 
1 index capacity Because size of index very large example size of index is 2 gb i want size of index is 1 gb or fewer
2 i want move file index in other location example my index in drive c but  i want in other drive example d but not in kiwix

**Comment by kelson42** [comment]
New version 2.0 of Kiwix Desktop does not allow to index content, as the index is already embedded in the ZIM file. This solve the bug.
