### ISSUE TITLE
Custom apps seemed to stop to work after update to 6.0

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#5]
@rgaudin
I'm pretty unsure about the reprocase but this was my impression that upgrading to android6.0 has broken wikimed app. Do you think this is possible?

**Comment by rgaudin** [comment]
No idea. What's the problem now? Crash at start? Do you have a trace?

**Comment by kelson42** [comment]
The app refused to start at all for the rest I didn't react correctly at the time it occured. I think I better close that bug because without additional information we are not going to go further. Next time you or I have a device to upgrade, we should open an eye to this.
