### ISSUE TITLE
DownloadManager notification

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#50]
When you click on an Item in the LibraryActivity.java for now, it will only create one notification for a downloaded item, since the notification ID is hardcoded.
It doesn't handle multiple items being downloaded at the same time.

Implement:
- A notification for each downloading item
- Dismiss notification once the download is finished
- Dismiss notification once the download service is stopped

---

To launch the DownloadManager, you need to start the LibraryActivity yourself, which at this point is not called nowhere from within the app since it's still very experimental and not integrated yet.

**Comment by mhutti1** [comment]
d7edb7712cc7a6c261729319040793a4621802bd
