### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by amirh123123** [kiwix/kiwix-xulrunner#501]
hi i have 2 question 
1 i go to iiab.me:3000 kiwix server i see CDC Extract
but not zim file in download.kiwix.org why it's not
2 
When does it take to creat wikipedia zim example wikipedia en all novid thanks

**Comment by kelson42** [comment]
iiab bug should be reported on iiab side.

**Comment by Klimmbimmel** [comment]
Please close
