### ISSUE TITLE
zim sertch

### ISSUE THREAD

**Issue by amirh123123** [kiwix/kiwix-xulrunner#502]
hi please add google sertch for zim files thanks

**Comment by kelson42** [comment]
Can you please give a detail use case? I do not understand what is meant here? Google search in an online tool, and we are talking about a custom offline content? What is the problem you try to fix?

**Comment by amirh123123** [comment]
please add google sertch offline 
and please read my older comments thanks

**Comment by kelson42** [comment]
Online google service can not reach offline ZIM content. Impossible to do.
