### ISSUE TITLE
Search doesn't find all articles with hyphen

### ISSUE THREAD

**Issue by Klimmbimmel** [kiwix/kiwix-xulrunner#506]
But kiwix doesn't behave predictable.

* FM-Synthese doesn't show up, even if you type "FM" (or more)
* La Ville-aux-Dames does show up as long as you didn't type the first letter or more after the first hyphen
*Jean-Michel <whatever last name> is found in all cases of search string. (Even 2 last names separated each by white space.) 

So maybe it has to do with the order of the white space and the hyphen?

I'm using LineageOS with kiwix, newest release on F-Droid, 2.2 build 47

**Comment by kelson42** [comment]
@Klimmbimmel Which ZIM/Content includes the arrticles you are talking about?

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-tools#156
