### ISSUE TITLE
Create a database for current files

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#51]
As of now, every time you open up the ZimFileSelectActivity, the app scans the entire system for new zim files. 
It would be better to save the files that we already know of in a database, and then once you open up the ZimFileSelectActivity, display at least those files, and start refreshing for new content in the background.
Use the current implementation of [squidb](https://github.com/yahoo/squidb) in the /database/ package for this.

Additionally, the database should not only save the paths to the files, but also the meta data for the zim file (Author, publish date etc.). All this can be found out by using `ZimContentProvider.setZimFile()`

**Comment by runnig** [comment]
Assigning to myself.

**Comment by mhutti1** [comment]
8fb768906605728a289d9f97c9705f3613c80bcb
