### ISSUE TITLE
Parse metafiles with simple xml with Retrofit

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#52]
Find a way to parse a metafile like [this](http://download.kiwix.org/zim/wikipedia/wikipedia_af_all_nopic_2016-05.zim.meta4), using simple xml.

An example on how to use simple xml can be found by looking at `LibraryNetworkEntity.java`.
Convert the `MetaLinkNetworkEntity.java` for parsing the meta link files to a similar entity. 

Currently, the meta links are parsed by setting a custom `ConverterFactory` for retrofit: `MetaLinkConverterFactory.java`. It uses regex to find out the mirror urls, which is very suboptimal, since we'd also like to have the hash values and all the other data from the meta files.

**Comment by iinozemtsev** [comment]
I'm taking it

**Comment by iinozemtsev** [comment]
Sent #239

**Comment by kelson42** [comment]
Looks like this ticket is done :)
