### ISSUE TITLE
Remove custom LayoutInflatorFactory for custom fonts

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#56]
Kiwix uses custom fonts to render unsupported Languages (see LanguageUtils.java). 
But the custom language-changer solution is now a bit outdated. Replace the font changing with the library [Calligraphy](https://github.com/chrisjenx/Calligraphy).

**Comment by mhutti1** [comment]
This issue was moved to kiwix/kiwix-android#37
