### ISSUE TITLE
Impossible to build custom apps with embedded ZIM (anymore)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#6]
here is the log at the time the app is launched

03-02 20:13:53.200 31352 31352 D kiwix   : Kiwix Custom App starting for the first time. Check Companion ZIM.
03-02 20:13:53.204 31352 31352 D kiwix   : Looking for: /data/data/org.kiwix.kiwixcustomwikivoyage/lib/libcontent.so -- filesize: 4802267
03-02 20:13:53.205 31352 31352 D kiwix   : ... doesn't exist.
03-02 20:13:53.232 31352 31352 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's

On the screen, at the start, the following error message appears:
"Your application is corrupted. This might happen when you remove files on the SD Card...."

**Comment by rgaudin** [comment]
OK, it's pretty normal if your missing the custom ZIM at the desired location or its size mismatch.

``` java
if (!FileUtils.doesFileExist(filePath, Constants.CUSTOM_APP_ZIM_FILE_SIZE, false)) {
            Log.d(TAG_KIWIX, "... doesn't exist.");
```

Although the code does not state which test failed (presence or file size), it appears from testing that the problem is most likely the file is missing.
Can you save us some time by checking:
- The APK is large enough to contain the content
- The actual presence at specified path on device of the libcontent.so
- Its size if it's there
- Try looking around for a different path if it's not there. Is it on the same device that upgraded to 6.0?

**Comment by mhutti1** [comment]
Not using symlinks when creating the content-libs.jar that then gets embedded into the apk seems to have fixed it for me.

**Comment by kelson42** [comment]
@mhutti1 
I have rollbacked your fix not because it does not work but because that creates a duplicate of the content in the APK (x4, one time per arch)

@rgaudin 
I have implemented a better log for FileUtils::doesFileExists and the conclusion is that:
- The APK contains the ZIM file one time
- The ZIM file (or libcontent.so) seems to be at the right place for one architecture
- The other archs have symlinks in the source and ZIP. But the problem is that symlinks seems not correctly unpacked on Android. I guess the unpacker of Android is not able to deal with this. Instead it creates a file with the content like it is store in the ZIP file (a file with the symlink target as content: "../mips/libcontent.so")

I wonder if this has already worked in the past!

Here the log:
D/kiwix   ( 7516): Kiwix Custom App starting for the first time. Check Companion ZIM.
D/kiwix   ( 7516): Looking for '/data/data/org.kiwix.kiwixcustomwikivoyage/lib/libcontent.so' with size=4802267
D/kiwix   ( 7516): File '/data/data/org.kiwix.kiwixcustomwikivoyage/lib/libcontent.so' found but with wrong size=21

**Comment by kelson42** [comment]
@rgaudin
Do you remember why you used that way instead of putting the ZIM file int he "assets" like "icudt49l.dat"?

**Comment by rgaudin** [comment]
I don't remember the why but I remember it was the only was to make it work
and I did test on multiple arches : arm and Intel (your device).
So it used to work. We could retest on 4.x and 5.x though.

Maybe the app can access the file but gets the symlink file size and fails
this way?
Can you try to bypass the file size check and test?

**Comment by kelson42** [comment]
@rgaudin 
I'll test. I forgot to say that I test on my "old" ICS tablet.

**Comment by mhutti1** [comment]
I suggest adding in the option to compile for specific architectures to reduce app size. Distributing ZIMs in APKs results in a duplicate of the ZIM when android unpacks it so is always going to be inefficient. Ultimately it looks like it might be possible to move it into assets or res/raw but its not a nice solution to still allow binaries to access it.

**Comment by kelson42** [comment]
@mhutti1 We want "universal app" to allow all users to deal with the app.

**Comment by mhutti1** [comment]
@kelson42 In that case putting it in assets and then copying to SD is probably the best way to achieve this. There will still be a duplicate but it will be 2/5 the size of keeping it in the libcontent.so I will look into this.

**Comment by mhutti1** [comment]
I have moved the embedded zim out of the lib folder and into the assets folder. It then gets copied out and read as the icudt49l.dat is.

**Comment by rgaudin** [comment]
Thanks Isaac. What archs and version are you testing against?

@kelson I think we should test this on multiple archs and android versions.
I'd love to be wrong be I clearly remember going all the (painful) way to a
.so for a reason.
Will try to look at the code Tom. to see if it rings some bell.

**Comment by mhutti1** [comment]
I am testing on android 6.0 and armeabi-v7a nexus 7 (2013) and Moto G 1st gen

**Comment by kelson42** [comment]
@rgaudin Currently, at least to me, it's pretty easy to test because the libcontent.so is installed in the mips arch directory. So arm devices. what you probably have, fails.

**Comment by kelson42** [comment]
Current status:

We really need to fix that problem because for a medical project we need to be able to distribute customapps outside the Google Play app store. These last days @mhutti1 has fixed many bugs/regressions related to the custom apps and everything works fine again except for this last problem. After our discussions and test, it seems impossible to provide an APK with only one time the ZIM file in the APK and on the storage one time the app is installed and this for all architectures. We have to chose between this alternative:
1 - Put the ZIM file as a library (like @rgaudin did) and make an APK only for on architecture (armeabi)
2 - Having the ZIM file in the "assets" and copy it to the filesystem at first start but then you have it two times on the filesystem.

Currently on 'master' it's (2) is implemented but for me it does not work. The appk is not able to load the ZIM file at the first start.

**Comment by mhutti1** [comment]
@Kelson42 We have another option now but I don't know if you would prefer it. Distribute the app without the ZIM and then require its download upon initial launch with a instinctive UI.

I will look into the problem with 2 though.

**Comment by kelson42** [comment]
@mhutti1 No, because we need this for pure offline distribution... But otherwise, yes this is IMO the ultimative approach to follow. Thanks for having a look... again...

**Comment by mhutti1** [comment]
@kelson42 I just thought about another approach. Have we tried using expansion files?
or does that not work without play store :(

Edit: looks like WikiMed does use expansion file from play store.

**Comment by mhutti1** [comment]
@kelson42 or does that not work without play store :(

**Comment by mhutti1** [comment]
@kelson42 Just tested and 2 works fine for me. Can I have log please.

**Comment by rgaudin** [comment]
Expansion files are distributed _by_ the play store (and thus automatically
downloaded).
Using it outside the store is as useful as providing the zim separately
with added constraints of file size limit (2G) and lost interoperability of
zim file...

**Comment by kelson42** [comment]
@mhutti1 

I have tested again and indeed with a smalr ZIM file it works but not with a bigger one like for wikimed.

Here is the command I run
./gen-custom-android-build.py customapp/wikimed/info.json
in customapp/wikimed/info.json, i have changed "embed_zim" to true
I have downloaded http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2016-07.zim to customapp/wikimed/content.zim

The following error message appears then, it seems to have a memory problem:

```
D/StatusBarManagerService( 2809): manageDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams
D/kiwix   (  421): Setting the ICU directory path to /data/data/org.kiwix.kiwixcustomwikimed/files/icu
E/filemap (  421): mmap(0,1036699366) failed: Out of memory
W/asset   (  421): create map from entry failed
E/kiwix   (  421): Error copying ZIM data file
E/kiwix   (  421): java.io.FileNotFoundException: content.zim
E/kiwix   (  421):  at android.content.res.AssetManager.openAsset(Native Method)
E/kiwix   (  421):  at android.content.res.AssetManager.open(AssetManager.java:330)
E/kiwix   (  421):  at android.content.res.AssetManager.open(AssetManager.java:304)
E/kiwix   (  421):  at org.kiwix.kiwixcustomwikimed.ZimContentProvider.loadZIMData(ZimContentProvider.java:196)
E/kiwix   (  421):  at org.kiwix.kiwixcustomwikimed.ZimContentProvider.setZIMDataDirectory(ZimContentProvider.java:355)
E/kiwix   (  421):  at org.kiwix.kiwixcustomwikimed.ZimContentProvider.onCreate(ZimContentProvider.java:234)
E/kiwix   (  421):  at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
E/kiwix   (  421):  at android.content.ContentProvider.attachInfo(ContentProvider.java:1692)
E/kiwix   (  421):  at android.app.ActivityThread.installProvider(ActivityThread.java:5674)
E/kiwix   (  421):  at android.app.ActivityThread.installContentProviders(ActivityThread.java:5269)
E/kiwix   (  421):  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5209)
E/kiwix   (  421):  at android.app.ActivityThread.access$1600(ActivityThread.java:181)
E/kiwix   (  421):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1535)
E/kiwix   (  421):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/kiwix   (  421):  at android.os.Looper.loop(Looper.java:145)
E/kiwix   (  421):  at android.app.ActivityThread.main(ActivityThread.java:6117)
E/kiwix   (  421):  at java.lang.reflect.Method.invoke(Native Method)
E/kiwix   (  421):  at java.lang.reflect.Method.invoke(Method.java:372)
E/kiwix   (  421):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/kiwix   (  421):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

I think the best solution would to have:
- Working like it is today also with bigger files
- Implement option " --on=ARCH" (like on ./build-android-with-native.py) on ./gen-custom-android-build.py (this is trivial)
- In case we have embed_file option and only one arch, then just copy the ZIM file in the system/lib directory like it was done at the beginning (see revision log, end of june 2015).

Doing so we would have the choice between being really portable but x2 mass storage usage and a little bit less portable (but ARM as my guess ~95% of the market anyway) and then small APK and optimal mass storage usage on the device.

and then to allow to compile this kind of app only for one archicture, for example by implementing

**Comment by mhutti1** [comment]
@kelson42 I just tried and it worked absolutely fine for me...  Are you running out of disk space or does your device have an unusually low amount of ram?

**Comment by mhutti1** [comment]
I reverted back to the lib solution but now I am having certificate problems. The sign application doesn't like signing libcontent.so Apparently the solution is to take out the bad files and sign them separately.

**Comment by mhutti1** [comment]
I am now working on the specific architecture options but calling --on=armeabi on the vanilla script doesn't work either. Am looking into it now.

**Comment by mhutti1** [comment]
I spend a very long time trying to add architecture specific options to the custom gen script and I think I have finally achieved It but I now need to test with a few more parameters. Firstly the standard and custom scripts have almost nothing in common. Then it turns out that while --on=armeabi would only compile for armeabi, it would package anything already in the libs directory into an apk.

**Comment by kelson42** [comment]
@mhutti1 Thank you very much for your effort

I have run : ./gen-custom-android-build.py customapp/wikimed/info.json. Is that the right command to compile only for armeabi?

By doing so I get an errror at the end:

```
-----------
/home/kiwix/kiwix/platforms/aarch64-linux-android/aarch64-linux-android/bin/strip /home/kiwix/kiwix/android-custom-LAJIr5/libs/arm64-v8a/libkiwix.so
-----------
Created locales.txt file.
-----------
ls -lh build/outputs/apk/org.kiwix.kiwixcustomwikimed-*
-----------
ls: cannot access 'build/outputs/apk/org.kiwix.kiwixcustomwikimed-*': No such file or directory
Traceback (most recent call last):
  File "./gen-custom-android-build.py", line 637, in <module>
    main(jspath, **options)
  File "./gen-custom-android-build.py", line 604, in main
    step_func(jsdata, **options)
  File "./gen-custom-android-build.py", line 469, in step_embed_zimfile
    os.path.join(tmpd, 'lib', architectures[0], jsdata.get('zim_name')))
IndexError: list index out of range

```

**Comment by mhutti1** [comment]
@Kelson To compile for specific architecture use e.g --on=armeabi I think I have fixed the bug you faced when not selecting any architectures in the command.

**Comment by kelson42** [comment]
Now I have an other error with
`$ ./gen-custom-android-build.py customapp/wikimed/info.json --on=armeabi`

```
/home/kiwix/kiwix/android-custom-K_Lgry/src/org/kiwix/kiwixcustomwikimed/KiwixMobileActivity.java:1626: error: cannot find symbol
            zimFileMissingBuilder.setMessage(R.string.customapp_missing_content);
                                                     ^
  symbol:   variable customapp_missing_content
  location: class string
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

Does it work well for you?

**Comment by mhutti1** [comment]
Looks like that string should be custom _app not custom app. I will try
work out why it's not.

**Comment by mhutti1** [comment]
422e4fdc90e8225638c40d1a1574ae70bc161ed8 broke that. I think I fixed now.

**Comment by kelson42** [comment]
The apps compiles but I get an error during the install process:

```
W/System.err( 2809): remove failed: ENOENT (No such file or directory) : /data/app/vmdl617828967.tmp/lib
W/System.err( 2809): remove failed: ENOENT (No such file or directory) : /data/app/vmdl617828967.tmp/lib/arm
E/filemap ( 2809): mmap(0,1036697444) failed: Out of memory
W/zipro   ( 2809): ExtractToMemory failed with File mapping failed
I/NativeLibraryHelper( 2809): Failed uncompressing libcontent.so to /data/app/vmdl617828967.tmp/lib/arm/tmp.b3I1F1
W/NativeHelper( 2809): Failure copying native libraries [errorCode=-18]

```

But with a smaller file it works

Would that helps do you think if we split the ZIM file in chunks?

**Comment by mhutti1** [comment]
I compiled with one architecture and all but could only test the single
architecture because of space limitations. It worked on my tablet. I think
the problem is not related to the code now but the limitations of android
itself (or your device). It simply can't copy that large a library. Do you
still get that error when using a specific architecture build or when using
a smaller zim?

**Comment by kelson42** [comment]
@mhutti I compile only with one architecture, not sure about how behaves the software otherwise currently. But do you think the problem comes from the APK size of from the ZIM size? Do you think if we have a splitted ZIM file this is goind to work better?

**Comment by mhutti1** [comment]
@kelson42  if you compiled for a specific architecture and it failed for you and not for me then I guess splitting the ZIM file up might work. I don't think the python script can handle this though and it might require a substantial amount of java changes as well. As a side note what os / device are you testing on. I have nexus 7 running marshmallow and its working fine.

**Comment by mhutti1** [comment]
@kelson42  As another thing try kill absolutely everything on device to minimise its memory usage and try again.

**Comment by kelson42** [comment]
@mhutti1 has found I believe probably a way to finally fix perfectly this problem http://www.50ply.com/blog/2013/01/19/loading-compressed-android-assets-with-file-pointer/#comment-1850768990

**Comment by kelson42** [comment]
I remove this from mileston 2.0 has the original bug is fixed.

**Comment by kelson42** [comment]
This problem is fixed but I have open a feature request to make is more robust #297. Thank you again @mhutti1 for the really good support and work on that really not-so-easy problem. Like you probably know pilots are currently running to distribute this kind of APKs with Wikipedia medical content in a few hospitals.
