### ISSUE TITLE
Give siebrand and niklas push access for translatewiki.net updates

### ISSUE THREAD

**Issue by siebrand** [kiwix/kiwix-xulrunner#7]
Can you please give @siebrand and @nikerabbit push access to the Kiwix repo? I just noticed today that our commits fail because we don't have push access.

**Comment by kelson42** [comment]
Have sent to you an invitation. Niklas was already member, so he should already have the permission to commit to "maintenance".

**Comment by kelson42** [comment]
So I know, this has been done.
